### ISSUE TITLE
Add operational playbook for updating external database versions

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/about#1099]
This page should describe actions that can be taken in 30 minutes or less to update the external database version of Sourcegraph. 

Part of RFC 174 https://docs.google.com/document/d/1zNy-9QTAS4-i4C-ooFsfSwLf-kdnIJlTE8-uyub6-Ik/edit?disco=AAAAGp1fgTs

**Comment by tsenart** [comment]
@daxmc99: Please all issues properly so that they show up in the tracking issue.
