### ISSUE TITLE
Pricing page on mobile has bad spacing and wrapping

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#1172]
On an iPhone at https://about.sourcegraph.com/pricing/:

![image](https://user-images.githubusercontent.com/1976/86995237-4e6b5e00-c15d-11ea-9876-a108cd683e6d.png)

![image](https://user-images.githubusercontent.com/1976/86995264-5f1bd400-c15d-11ea-8331-7f0585075040.png)

And we should not have the checkmark-features wrap:

![image](https://user-images.githubusercontent.com/1976/86995287-735fd100-c15d-11ea-9e58-650833560aaf.png)

**Comment by aileenrose** [comment]
It's probably best to go full-width for readability.  Tall feature boxes are a challenge for mobile viewers.   We could explore highlighting the key features and add a separate page with the feature comparisons.  example: https://about.gitlab.com/pricing/
