### ISSUE TITLE
iMessage link preview of about.sourcegraph.com has undesired animation

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#1174]
Repro:

1. On iOS Safari, visit https://about.sourcegraph.com
1. Click the iOS Safari share button
1. Click iMessage

Expected: the link preview is our logo icon
Actual: it's our logo icon, except it is a glitchy-looking animation of it zooming in and out

I'll try to get a video of this if you can't repro it.

**Comment by aileenrose** [comment]
I found the bug.  I added a duplicate meta tag which caused the summary card to reload the image. Fixed in: 
 https://github.com/sourcegraph/about/pull/1179
