### ISSUE TITLE
team-collaboration.md missing

### ISSUE THREAD

**Issue by Akkuma** [sourcegraph/about#1279]
https://github.com/sourcegraph/about/blob/master/handbook/engineering/hiring/index.md references https://github.com/sourcegraph/interviews/blob/master/engineering/team-collaboration.md, which doesn't appear to exist

**Comment by sqs** [comment]
from @nicksnyder 

We currently have a broken link that got merged into master in the handbook (red build doesn’t prevent merging), but there isn’t a red build on master because netlify checks don’t run on merge? How does stuff get deployed once it is on master?

**Comment by nicksnyder** [comment]
It exists, it is just private and only visible to Sourcegraph employees. 

See this note at the top of the handbook page:

> Most of our process is documented in a private repository, but our goal is to move as much as possible into the handbook.
