### ISSUE TITLE
Add pronounciation info next to team member names

### ISSUE THREAD

**Issue by serkandurusoy** [sourcegraph/about#1335]
As the company is growing internationally, it would help job applicants and new hires to know how to pronounce team members' names on the [team](https://github.com/sourcegraph/about/blob/master/company/team/index.md) page.

This could be done by adding [IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet) notation and audio files similar to how Wikipedia does it, especially for international names.

**Comment by nicksnyder** [comment]
We do ask teammate's to add how their name is pronounced by recording an audio file; [see the template](https://about.sourcegraph.com/company/team):

>- Name pronunciation (record an audio file from your phone [here](https://www.name-coach.com/))

Some teammates have not added a recording yet.

**Comment by efritz** [comment]
Sample: https://github.com/sourcegraph/about/pull/1338

**Comment by serkandurusoy** [comment]
Thank you guys both for quickly jumping in to reply.

So, it turns out only 8 out of 51 people have added that.

But, I also realize now that my source of inspiration for this was their bios yet Wikipedia kept popping up in my head instead, so I connected the wrong dots.

So I was more or less recommending you do this thing that this cool company whose name I could not remember (_Sourcegraph_) does ;)

Please write that off to my lack of sleep at 3am :)
