### ISSUE TITLE
social media preview for repository is not legible on light backgrounds

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/about#1431]
I don't imagine a lot of people see this since we don't seem to share this repository specifically very often

<img width="656" alt="Screen Shot 2020-08-24 at 9 30 11 AM" src="https://user-images.githubusercontent.com/23356519/90996488-7e799e00-e5f1-11ea-8297-0747da4b5764.png">

**Comment by sqs** [comment]
Removed it for now. Thanks for reporting.
