### ISSUE TITLE
Can't preview scripts locally

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/about#1484]
When I run the handbook locally with `make serve`, I can't see the rendered team page: http://0.0.0.0:5082/company/team/org_chart#engineering or goals http://0.0.0.0:5082/company/goals. The JavaScript is getting escaped. Not sure why this behavior is different then what happens on about.sourcegraph.com

cc @sqs

**Comment by sqs** [comment]
Try building the latest docsite binary. Does that work?

**Comment by nicksnyder** [comment]
No, doesn't seem to.

```go
nick@Nicks-MBP about % GOBIN=${PWD}/.bin go install github.com/sourcegraph/docsite/cmd/docsite
nick@Nicks-MBP about % .bin/docsite serve -http=:5082
# Doc site is available at http://0.0.0.0:5082
```

**Comment by nicksnyder** [comment]
Oh, version in go.mod needed updated.

**Comment by sqs** [comment]
Thank you!
