### ISSUE TITLE
GopherCon 2019 liveblog updates

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/about#158]
Resize and update the current Gophercon default image ![](https://about.sourcegraph.com/gophercon2019.png) with 
![thumb_1200x1200_3](https://user-images.githubusercontent.com/133014/61889241-eb37db80-aeb9-11e9-9ba1-271c37d8b837.png)

**Comment by attfarhan** [comment]
Fixed https://github.com/sourcegraph/about/commit/ce2c193acbfdc3a63992ecf320d31e25601a5b3f
