### ISSUE TITLE
Levels of transparency table not rendered correctly

### ISSUE THREAD

**Issue by jeanduplessis** [sourcegraph/about#1595]
## Problem

The Level of transparency table is not rendering correctly on the values page.
https://about.sourcegraph.com/company/values#open-and-transparent

![93518289-e7241400-f92c-11ea-8ec8-91bb5fae6963](https://user-images.githubusercontent.com/492942/93518672-703b4b00-f92d-11ea-8455-f3cc38dc658f.png)

## Further information

Change was introduced in https://github.com/sourcegraph/about/pull/1515

**Comment by christinaforney** [comment]
Thanks for filing @jeanduplessis !

@kghopson can you take a look please?

**Comment by nicksnyder** [comment]
I had a hunch and I was correct. This was fixed by https://github.com/sourcegraph/about/commit/40f2c89d44868ca0e6d4194f6387a01619d241cb

Our markdown renderer is not as forgiving as what GitHub uses.
