### ISSUE TITLE
Proposal: make link in the top-left corner the handbook (and all docsites) go to /handbook (and be customizable generally)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/about#1602]
I often click that link hoping it will take me back to the handbook homepage, only later realizing that it jumped me to about.sourcegraph.com. I know there's usually a link to the handbook homepage in the breadcrumbs right beneath it, but I still find the icon's behavior unexpected. 

And on search results pages, there ARE no breadcrumbs, so there is no easy/obvious way to get back to the handbook homepage without URL hacking.

Note we also already have a link to "About" in the top-right corner.

I would have just gone and changed this myself, but it appears that there's no way to do so for a single docsite... Any changes to the same template at https://sourcegraph.com/github.com/sourcegraph/about@main/-/blob/_resources/templates/root.html#L33:7 would also affect the /company pages as well it seems.

So filing this as a tracking issue.

**Comment by marybelzer** [comment]
This was resolved with the release of the new handbook, closing this issue.
