### ISSUE TITLE
Add Criteo case study to website

### ISSUE THREAD

**Issue by lorihey** [sourcegraph/about#1810]
Please grab the content from here:

https://docs.google.com/document/d/141_HJ97XXcX42L6QDzCXN84mdOzzq-JijigQqe2NsUQ/edit?pli=1

Please use both Loic's and Francois' photos (attached).
![Loic](https://user-images.githubusercontent.com/66978976/96801186-e7944c80-13bb-11eb-9371-272edb51e821.jpg)
![Francois](https://user-images.githubusercontent.com/66978976/96801190-e95e1000-13bb-11eb-98c5-a61d1a9da5cb.jpg)

**Comment by aileenrose** [comment]
done.
