### ISSUE TITLE
Show "Search for symbol" instead of "Go to definition" and "Find references" when they are imprecise

### ISSUE THREAD

**Issue by macraig** [sourcegraph/about#1966]
Show a "Search for symbol" button instead of "Go to def" or "Find references" if code intel is search-based. This would replace the alert disclaimer in the case below:

![Screenshot 2020-11-05 at 18 07 20](https://user-images.githubusercontent.com/1657213/98398523-65fe1900-2061-11eb-82f2-890d9b73e68e.png)

**Comment by efritz** [comment]
@sourcegraph/web Can we discuss what the difficulty of doing this would be? Seems like there's not enough data in the current extension API in order to achieve what we want from the UI here. Tips welcome!

**Comment by felixfbecker** [comment]
How would prefer this functionality to be exposed in the API?

**Comment by felixfbecker** [comment]
BTW is there a reason this is filed in the `about` repo and not in the main repo?

**Comment by macraig** [comment]
@felixfbecker ugh no, I must have opened it here by mistake, closing and moving to [main](https://github.com/sourcegraph/sourcegraph/issues/17617)
