### ISSUE TITLE
Gatsby dev server: page reloads page continuously

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#2015]
I tried to run the website in a dev server `cd website && yarn && yarn run start` and (after fixing #2014) am seeing a problem where the page (such as `/blog`) continuously reloads in my browser. It shows up for a split second and then reloads, and this repeats 20-ish times until it finally stops reloading and then the page appears.

There's 1 error in the JS console that shows up on each page load. I don't know if this is related.

```
VM1809:1 Uncaught SyntaxError: Identifier 'cookieDialog' has already been declared
    at CookieControl.Dialog.createCustomScript (VM1793 cc.js:1)
    at CookieControl.Dialog.runCustomScript (VM1793 cc.js:1)
    at CookieControl.Dialog.displaydialog (VM1793 cc.js:1)
    at CookieControl.Dialog.show (VM1793 cc.js:1)
    at CookieControl.Dialog.init (VM1793 cc.js:1)
    at VM1793 cc.js:63
```

**Comment by aileenrose** [comment]
I'm unable to reproduce this.   I started up a server with those commands you noted and looked at /blog and /podcast, plus I ran those pages also in Incognito windows.  The JS console did not display those errors.  
The only thing I noticed is a delay in rendering the CSS.   I am not familiar with the differences between running `yarn run start` vs `yarn serve`.   I'll read up on it and keep this open in the meantime.
