### ISSUE TITLE
Add CERN case study to website

### ISSUE THREAD

**Issue by lorihey** [sourcegraph/about#2189]
Please grab the content and photos from here:

https://docs.google.com/document/d/1_qMAkSI855WPnWiM-dzNh3JhiL9WgT1f01bONdYHsvE/edit?usp=sharing

**Comment by lorihey** [comment]
Additional instructions from CERN today:
"Official Logo (attached) that you should use.
[CERN_Supplier_Logo.zip](https://github.com/sourcegraph/about/files/5710293/CERN_Supplier_Logo.zip)
 I hope the file format is OK. You should also link link the  logo to the CERN procurement service: https://procurement.web.cern.ch/ so that if someone clicks on the logo, s/he is taken to our site."

**Comment by aileenrose** [comment]
https://github.com/sourcegraph/about/pull/2191
