### ISSUE TITLE
Working title: How we built (and re-built) Campaigns

### ISSUE THREAD

**Issue by content-hacker** [sourcegraph/about#2375]
# Working Title: How we built (and re-built) Campaigns 

- **Category:** Engineering
- **Theme:** A behind the scenes look at creating Campaigns 
- **Type:** Ongoing series 
  - Issue 1

## Pitch

The first Campaigns themed engineering post covers the origin story of Campaigns and the decision making process the team used to arrive at the current iteration. This article investigates the journey of creating Campaigns: how we started building a solution for one problem, and through that process discovered the real problem to solve, and then pivoted to the product we have today. It is deep dive into the problem identification, solution discovery, and building the final output. 

1. What is Campaigns? 
2. How did you identify the need to create Campaigns? 
3. What problem does it solve? 
4. How did you arrive at the first iteration of Campaigns? How did you discover and validate that you needed to build something different? How did you repurpose your existing work? 

## Production details 

- Author: 
- Editor: @content-hacker 
- Contributors: 
- Publish timeframe: week of March 1 
- Related marketing campaigns: Campaigns Product Launch

[Audio transcript from call with Any and Thorsten] (https://zoom.us/rec/play/JkMWdnKdwwzLTbT1Kwl1at4gGiAzr-WJuqEPmBwIksYhsA4DudTzEL4BUaNrgzlkCyZaAn-gSQkuDs8v.lOEtBnzvHZ7NQhqr?continueMode=true)

**Comment by content-hacker** [comment]
@mrnugget can you help me identify who, in additional to yourself, should contribute to this article?

**Comment by mrnugget** [comment]
Contribute in what capacity? I think everybody on the campaigns team has something to share about the history of campaigns. Quinn Slack also, since he made two major pull requests that changed the direction of campaigns. I can't promise anything, but I'll see if I can write you a ... draft? (not sure if that's the right word here) to kinda show what I had in mind.

**Comment by content-hacker** [comment]
@mrnugget I'm looking for people who have subject matter expertise on the topic to contribute to the story gathering process and anyone who wants to participate in the writing and editing process. I'd like to follow the progress and evolution of Campaigns as a theme on our blog and build a library of interviews, facts, and evidence that we can use in various content pieces. Since this is a larger project than writing a blog post, I will create a separate thread for that. 

If you would like to author this post, that would be great! Please add yourself as an assignee to this issue. My goal is to publish this as the first post in a series following the evolution of Campaigns. This is in coordination with the Campaigns product launch scheduled for the first week of March. I will share a work back timeline with key milestones we'll need to hit over the next 6 weeks to meet the deadline. 

The current angle is a post that covers the origin story of Campaigns and the decision making process the team used to arrive at the current iteration. If you have something else in mind instead of or in addition to this angle, a pitch would be a great place to start. A pitch only needs to include the rough idea and key points of what you want to cover. It doesn't need to be a fully thought through draft.

**Comment by mrnugget** [comment]
Thanks, that's useful info.

I once wrote a little [historical recap](https://docs.google.com/document/d/1IzGlUq3szrUAeacUnowg2ImP0zKUxoLhdD7La-4PyhY/edit#heading=h.vz6je5nolonk) of the stages campaigns went through. It's written under a different angle (user focus) but it might already give you a glimpse of "the origin story of Campaigns and the decision making process the team used to arrive at the current iteration".

> A pitch only needs to include the rough idea and key points of what you want to cover. It doesn't need to be a fully thought through draft.

Great! I'll try to come up with something.

**Comment by content-hacker** [comment]
@rebeccadee this was [published](https://about.sourcegraph.com/blog/avoiding-the-pitfalls-of-iteration-based-development/), going to close out the issue.
