### ISSUE TITLE
Blog post: How non-engineering teams can utilize Sourcegraph

### ISSUE THREAD

**Issue by content-hacker** [sourcegraph/about#2470]
Copying from the original note: 

Examples:: use campaigns for company address changes, legal departments sometimes need to comb through codebases, audit everywhere a HubSpot form is, data science use cases)

**Comment by ebrodymoore** [comment]
So... FYI @content-hacker @rebeccadee -- after what feels like 3 years of not working on this, @Joelkw and I started it [here](https://docs.google.com/document/d/1X8A09kMQi94IPxnCF_tFW-30IdZ_xRD94vTbDg5IZA4/edit#). We'll let you know when we have a better outline or first draft!
