### ISSUE TITLE
Create Intercom like widget 

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/about#280]
A replacement for the Intercom widget that makes it easy to jump to the most often viewed docs, contacting us, and submitting a support request.

**Comment by sqs** [comment]
@dadlerj Is this something you want? If not, let's close it.

**Comment by dadlerj** [comment]
This'll be a decision for Aileen and Adam, happy to close for now, but it's something I wouldn't mind keeping around for the time being in "backlog"
