### ISSUE TITLE
[handbook local dev error] template error: walking templates: walk /search.html: parse template search.html: template: root:18: function "highlight" not defined

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/about#334]
Following the README for local handbook dev (https://github.com/sourcegraph/about#handbook):

* On latest master
* Run: `docsite serve -http=:5081` from the repo root
* Visit http://0.0.0.0:5081 in Chrome
* See this error: `template error: walking templates: walk /search.html: parse template search.html: template: root:18: function "highlight" not defined`

I'll look more into this if the issue isn't an obvious one.

**Comment by sqs** [comment]
Update docsite to the latest and try again. Should fix it.
