### ISSUE TITLE
Product research form has unintentional large text

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#3456]
At  https://info.sourcegraph.com/product-research I see:

![image](https://user-images.githubusercontent.com/1976/123342573-d5e3e580-d504-11eb-93e8-89e0219aee62.png)
 
The `If you'd prefer not to share...` and `Sourcegraph is committed to...` text is too large.

**Comment by mgyorffy** [comment]
@marybelzer 
This will need to be fixed in Hubspot on this page:
https://app.hubspot.com/content/2762526/edit/41805212622/content
It might be an issue within Hubspot ...
FYI - I don't have publishing permissions in HubSpot.

**Comment by bretthayes** [comment]
- Fixed the font-size inconsistencies
- Also added a margin to the labels beside checkboxes since they were too crammed against each other
