### ISSUE TITLE
Search does not index rendered content

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/about#361]
Searching for strings contained in rendered content does not currently work.

For example:
https://docs.sourcegraph.com/search?q=smtp&v=

However, `smtp` exists here:
https://docs.sourcegraph.com/admin/config/site_config

**Comment by sqs** [comment]
It shows up now: 
![image](https://user-images.githubusercontent.com/1976/69221368-f29b8880-0b2b-11ea-8ce7-92ceadccd6c9.png)

It would be nice for there to be an excerpt, but this is acceptable for now.
