### ISSUE TITLE
Update RFC template to use same role terms as on decision-making page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#3931]
The [handbook decisions page](https://about.sourcegraph.com/handbook/communication/decisions) defines roles like recommenders, deciders, approvers, etc.

The RFC templates (https://docs.google.com/document/d/1cGq41T354YtuAkODmIwhm51i2LcApvtTm4T0GyH7gu4/edit and https://docs.google.com/document/d/1vUp1A-j5xxnPn_rv3x3rWo8tbXJhIA5NggHLU6UofUc/edit) should be updated to use these terms, and the following bit (that makes it sound like the RFCs and decisions page are out of sync) should be removed:

> Our RFCs encode several of these roles already, with the “authors” serving as recommenders (and sometimes deciders) and the “approvers” containing a mix of approvers and input providers (and sometimes deciders).

**Comment by marybelzer** [comment]
@dadlerj Can this issue be closed as a result of the work in #4282 ?

**Comment by dadlerj** [comment]
Yes, thanks!
