### ISSUE TITLE
Document why we don't list specific numbers for experience in job descriptions

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#446]
A candidate asked (on Twitter DM @srcgraph):

> Hey Sourcegraph!
>
> My name is $NAME, and I'm interested in your code intelligence position. I'm considering applying because I'm looking for remote opportunities outside $COUNTRY.
>
> I was just wondering how experienced candidates are you looking for? I've finished my Master's thesis in August, and I've been working as a software engineer for 2 years now.

My reply:

> Hey there, we don’t have any requirement on specific length of experience. We have team members who’ve joined straight from high school/university or after 10+ years of working at somewhere like Google, and all kinds can be successful here. Looking forward to seeing your application!

We should document this for people who read (eg) https://github.com/sourcegraph/careers/blob/master/job-descriptions/software-engineer-code-intelligence.md and wonder why it doesn't list a certain number of years.

**Comment by nicksnyder** [comment]
Where do you think this documentation should live? In the job description itself?

**Comment by sqs** [comment]
Just a section somewhere in the engineering section of the handbook so we can link people to it (and so that team members and others who peruse the handbook internalize this knowledge).
