### ISSUE TITLE
Trouble accessing Sourcegraph Champion Form

### ISSUE THREAD

**Issue by abxhr** [sourcegraph/about#4774]
I had tried to open up the the Google form, present at the end of the page of `https://about.sourcegraph.com/handbook/marketing/becoming_a_sourcegraph_champion`, but the form seems to be restricted for access.

I had tried to access the same page through other devices, and other google accounts as well, but I still face the same problem.

![Capture](https://user-images.githubusercontent.com/42249391/134546820-9d2f6089-661b-453c-a809-b3909aa6b52f.JPG)

**Comment by samswag** [comment]
Hi @abxhr can you try again? Thanks for flagging this, I just removed the restrictions

**Comment by abxhr** [comment]
It works well now, thank you! 🚀

**Comment by samswag** [comment]
Thank you
