### ISSUE TITLE
Blogpost to promote Rijnard's CactusCon talk "Bug Hunting with Structural Code Search"

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/about#481]
We can either wait for the video, or just embed the slides and promote now.

Talk abstract at https://www.cactuscon.com/2019-talks-and-workshops/bug-hunting-with-structural-code-search

**Comment by rvantonder** [comment]
This is on my radar, I'll drive it. There are some things I want to polish still (so please hold). Will post an update here by Wednesday, 8 Jan.

**Comment by rvantonder** [comment]
Update: this is in progress. Should have a draft up by end of the week.

**Comment by rvantonder** [comment]
We can probably close this for now? Feel free to reopen if there was another action here.
