### ISSUE TITLE
@nickmyyz Felix gave some directions here: https://github.com/sourcegraph/about/pull/4814#issue-1008153583

### ISSUE THREAD

**Issue by nickmyyz** [sourcegraph/about#4932]
@nickmyyz Felix gave some directions here: https://github.com/sourcegraph/about/pull/4814#issue-1008153583

_Originally posted by @rebeccadee in https://github.com/sourcegraph/about/pull/4926#discussion_r722028014_

(Not sure how best to reply?) I tried the plugin Felix referenced here and couldn't get it to work. Have you tried it before?

**Comment by rebeccadee** [comment]
Closing, replied here: https://github.com/sourcegraph/about/pull/4926#discussion_r723994956
