### ISSUE TITLE
Make handbook fast to load

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#499]
The handbook is still often slow to load. I can reliably reproduce the slowness on search results pages:

```
$ while true; do echo search; time curl -sSL -o /dev/null 'https://about.sourcegraph.com/search?q=2019+model'; echo sales; time curl -sSL -o /dev/null 'https://about.sourcegraph.com/handbook/sales'; sleep 30; echo; done

search

real	0m6.751s
user	0m0.000s
sys	0m0.018s

sales

real	0m0.200s
user	0m0.016s
sys	0m0.004s
```

- [ ] Make search faster
- [ ] Set up external perf monitoring to help avoid regressions

**Comment by tsenart** [comment]
@sqs: Could you share / document how the handbook is deployed? If I had that information, I could timebox working on this soonish.

**Comment by tsenart** [comment]
Also, credentials in 1Password would be needed.

**Comment by sqs** [comment]
Yes, the handbook is deployed in the same way the docs.sourcegraph.com site is deployed. It's the `about-sourcegraph-com` deployment in the k8s `dot-com` cluster (default namespace). No extra credentials are needed, just GCP access. See https://github.com/sourcegraph/docsite#release-a-new-version for info on what the pod is actually running. The problem is that the `about` repo's zip archive is huge, and there is some combo of these problems:

1. maybe the pod is killed (OOM'd?) and then it needs to re-download the archive before it can serve any pages
2. it checks for a new repo zip archive (for `master`) each 5 minutes and is supposed to keep serving the possibly old version in the meantime, but there could be a bug
3. search is slow and unoptimized; there is no index

Thanks if you look into this!

**Comment by sqs** [comment]
Ahhh... I may have figured it out. Netlify's proxy may be the cause.

about.sourcegraph.com is running on Netlify, and we proxy `/handbook`, `/search`, and other handbook paths to https://about-docsite.sourcegraph.com. If I hit the about-docsite.sourcegraph.com host directly, it's very fast:

```
$ while true; do date; time curl -sSL -o /dev/null https://about-docsite.sourcegraph.com/handbook; time curl -sSL -o /dev/null 'https://about-docsite.sourcegraph.com/search?q=kubernetes'; sleep 15; done

Tue 11 Feb 2020 05:49:26 AM GMT

real	0m0.338s
user	0m0.009s
sys	0m0.000s

real	0m0.602s
user	0m0.005s
sys	0m0.005s


... etc ...
```

but when using https://about.sourcegraph.com (proxied via Netlify) it is much slower and has much higher variance (often 3-8s).

**Comment by sqs** [comment]
Great news! It seems consistently fast now. However, Netlify claims (in a [post from 29 min ago](https://community.netlify.com/t/consistent-6-second-ttfb-on-small-index-html-file/7359/27)) to not yet have solved this:

> We are actively working on this, but I am unable to provide a timeline.

I'm going to close this issue on our end because *something* seems to have improved a lot and has remained good for ~12 hours. But if we see this occur again, even briefly, let's reopen this issue.

**Comment by sqs** [comment]
Unfortunately, the intermittent slowness has returned. Running `time curl -v 'https://about.sourcegraph.com/search?q=sql'` 10 times in a row just yielded 3 fast (<1s) responses and 10 slow (6s) responses.

**Comment by creachadair** [comment]
> I will monitor this and see if we still need to switch away from Netlify in the next few days.

Given we already have a lot of assets in GCP, might it make sense to move there anyway? I would guess the incremental cost should not be that high over what we're already spending.

**Comment by sqs** [comment]
The slowness has been gone for a while. :tada: Closing.
