### ISSUE TITLE
Update website content to more accurately reflect what we support today

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/about#5011]
Relates to https://github.com/sourcegraph/about/issues/5230

Our current homepage lists many things that we could add support for (and can technically be made to work), but not all of these things are equally supported in a first class way. This marketing page served its purpose when we we wanted to attract a broad funnel of customers and then build support on-demand, but this is not going to be our approach moving forward, so we need to clean this up.

On the surface this is "remove all the things we don't support" (like SVN), but after doing that we might actually need to redesign the layout to make more sense.

![Screen Shot 2021-12-08 at 4 39 00 PM](https://user-images.githubusercontent.com/754768/145432420-45abdbfa-fa73-4cef-8416-929003333ce9.png)

**Comment by abschu** [comment]
@nicksnyder @jeanduplessis - we are planning on updating the homepage in April (and are working on the design this week). By the end of the week, can you please let us know what needs to be removed from this section so we can make sure it's accurate? Thank you! CC @fabicastp

**Comment by jeanduplessis** [comment]
@dan-mckean Could you confirm the code hosts that we support and what items under the "All your repositories" section should be removed/kept.

@muratsu Could you confirm the tools and editors we support through integrations and extensions and what items under the "All your tools" section should be removed/kept.

@benvenker @macraig Could you confirm the languages we support and what items under the "All your languages" section should be removed/kept.

@dan-mckean Could you confirm the deployment options we support and what items under the "Deployment options" section should be removed/kept.

Please confirm whether you can provide this information to @abschu by the end of this week (2022-04-01)

**Comment by macraig** [comment]
From the code intel perspective do we want to showcase precise support (in which case the list is short) or all the languages we support for search-based?

**Comment by dan-mckean** [comment]
### Supported deployments

I'd drop the who, where, what - you can't mix and match any option with any others from each of the three categories.

Instead, the options I'd suggest we include:
- Self-hosted by you 
  - Kubernetes - your own Kubernetes cluster, Amazon EKS or EC2, Google GKE, or Microsoft Azure AKS
  - Docker Compose
- Hosted by us (Docker Compose in GCP)

**Comment by abschu** [comment]
> ### Supported deployments
> I'd drop the who, where, what - you can't mix and match any option with any others from each of the three categories.
> 
> Instead, the options I'd suggest we include:
> 
> * Self-hosted by you
>   
>   * Kubernetes - your own Kubernetes cluster, Amazon EKS or EC2, Google GKE, or Microsoft Azure AKS
>   * Docker Compose
> * Hosted by us (Docker Compose in GCP)

@dan-mckean - would this work:
Self-hosted by you
Tags: Kubernetes - your own Kubernetes cluster, Amazon EKS or EC2, Google GKE,  Microsoft Azure AKS, Docker Compose

Managed and hosted by us
Tags: Docker Compose in GCP

**Comment by dan-mckean** [comment]
Looks good @abschu
