### ISSUE TITLE
Test if all 3 version numbers are correctly updated when the next release is done

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5051]
Asana ticket link: https://app.asana.com/0/1200095757619647/1201535874731660

About site:
home page / Get started section install script
code-search page / Get started section install script
new get-started page / install script

**Comment by mgyorffy** [comment]
The release will go out tonight at 10:00pm PT. I will be able to test it after that to see if all 3 locations where the install script is present the version number updates from 3.35.0 to 3.35.1

**Comment by mgyorffy** [comment]
I tested the two places in the code (that affect 3 places on the about site) and one of the two places were updated. I asked Kevin Wojkovich and he added the second script and merged the PR today.
So as of now:
1. All 3 locations are updated in production
2. And the updates will happen automatically for all subsequent SG product version updates
