### ISSUE TITLE
Customize CSS for ChiliPiper

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5060]
🔗[Slack thread](https://sourcegraph.slack.com/archives/C01SWQRPJAC/p1640101579052000)
🔗[Customize CSS for booking links (article)](https://help.chilipiper.com/hc/en-us/articles/360053023194-Customize-CSS-for-Booking-Links#h_01F6TD89F9B8VG6QF9P11436J3) - "We've gathered some of the most commonly changed styles here, but you are free to customize any elements on the booking pages that may not be included in this article".

To set custom styling for Booking links: 

1. Log in to Chili Piper
2. Click My Workspace, select Team CRM 
3. On left menu bar, scroll down to CSS Preferences 

Use the CSS Generator on [the article](https://help.chilipiper.com/hc/en-us/articles/360053023194-Customize-CSS-for-Booking-Links#h_01FDX17VTBN474KD5B2KCB8YDQ). Primary HEX color #5033E1. 
 
Additional requests to what's generated: 

Calendar screen and Form screen:
Add logo to upper right corner 

Concierge: Phone, and Video Selection
Header color: #FF5543
Content background color: grey
Selection buttons: 
Default background color: white
Default text color: keep as is
Background color when hovering: #5033E1
Text color when hovering: keep as is 

To preview work, use [this link ](https://sourcegraph.chilipiper.com/book/inbound-sdr-queue)

**Comment by mgyorffy** [comment]
Changes are done.
The only possible change to make is that I added the our logo with a hack, since Chili Piper has a bug, and that is why our logo is not showing up.
As soon as they fix it there will be two SG logos showing up, so I will remove the one I added.
