### ISSUE TITLE
Add Anyscale logo and quote to /cloud-beta

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5071]
Context
We have one beta customer, Anyscale, who just agreed to let us use a quote from them + their logo. 

Request:
Add the logo + quote at the top right of /cloud-beta 
While we’re at it, make small tweaks to the copy at the top of that page

Resources 
🖇️Customer logo (attached) 
💬 Quote: 
"Sourcegraph makes it so much easier to onboard to large codebases. It's an absolute game changer when it comes to navigating around an ecosystem with hundreds of repositories or even multiple organizations."
🔗[Copy doc for copy edits](https://docs.google.com/document/d/1AtYBFIVPnhiTQF0j8EHkcKvrTkwbCML6Lxj0p0aTCvs/edit) (January 10th version)

**Comment by marybelzer** [comment]
![0114ec37-170e-4864-b9a9-f85452de1ce0-1633971232076](https://user-images.githubusercontent.com/73856596/148993543-09c67f45-35ea-41b4-90bd-26a314983a02.png)

**Comment by mgyorffy** [comment]
Sure @marybelzer. It will take 1-2 hours to get it to review state, and depending on if the text changes break the layout and how the requestors are about those changes will be a little more potentially.

**Comment by marybelzer** [comment]
Thanks @mgyorffy - note that this is a lower priority than #5074

**Comment by marybelzer** [comment]
@mgyorffy Spoke with Steph and this was her suggestion: 

> What about using one of the modules (ex. "Find and fix security vulnerabilities") from the use cases page, which allows for explanatory text on the left, and a quote on the right? https://about.sourcegraph.com/use-cases
> 
> It would make more sense to me to add in a module than to add the logo/quote to the top of the page. It would be too crammed from a design/build perspective, but also overwhelming from a UX perspective.

Would we need to shrink the existing text to make this happen or would we be able to slightly rearrange?

**Comment by marybelzer** [comment]
@bretthayes Do you have an idea of when you'll be able to look at this? Thanks!

**Comment by bretthayes** [comment]
Going to do this today @marybelzer

**Comment by marybelzer** [comment]
Small copy change requested:

> can we have "—Alex Wu, Software Engineer at Anyscale" under the quote instead of "—Anyscale" ?
