### ISSUE TITLE
Get Started page bug

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5072]
When interacting with the get started flow on desktop, if the window is pretty short (shorter than my 13" Macbook Pro screen), the gradient boxes cover the header and make it difficult to scroll. 

See [this video](https://www.loom.com/share/6d36129736724fa4b2a32ebbf92c7a6a) Sarah created to see it in action.

This happens in three browsers I tested (Chrome, Firefox and Safari), it seems to be related to the window sizing rather than something browser specific. We should tackle this as part of the remaining get started work.

**Comment by marybelzer** [comment]
@mgyorffy I saw this was moved to done, but I'm still seeing the issue if I shorten my browser window. Are those gradient boxes static or can they adjust with the size of the window? If they're static my concern is that no matter what size we change them to, this will be a problem for someone's screen size. Is this something we should cover in the animations meeting tomorrow?

**Comment by mgyorffy** [comment]
If you decrease the height of your screen below 550px the issue will still happen, since I only decreased the height from 740px to 550px. That might be it.

**Comment by mgyorffy** [comment]
otherwise, this is done. the V2 dev work will resolve this issue completely by adding new pages instead of staying on the same page.
