### ISSUE TITLE
Sign up flow V1.1

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5081]
**Due for QA 1/18**

- [Figma file](https://www.figma.com/file/E3xF7awgMH2OcHfuWmrL0s/CTA-Optimization-%E2%80%93-Get-Started-Flow?node-id=608%3A2) - Go to Approved 1/13 tab. Get started flow V1.1. Make sure to read annotations 🗒️
- [Metadata](https://docs.google.com/spreadsheets/d/1R7PMEPoV7AEss5BkSMlf6RanY08hGGb-SBfvp1Mw9dg/edit#gid=536053404)

1. Create a new landing page to sign-up for cloud
2. Edit "Try it for free" CTA copy to "Get started for free
3. Change "Try it for free" CTA so it links to a new sign-up for cloud landing page
4. Update mobile version

Links

- Use [this page](https://sourcegraph.com/sign-up) to obtain the links to Sign up with GitHub and Sign up with GitLab. 
- Continue with email takes you to the landing page: https://sourcegraph.com/sign-up

**Comment by mgyorffy** [comment]
Ready for review on staging: https://deploy-preview-5083--sourcegraph.netlify.app/get-started

**Comment by mgyorffy** [comment]
ready for review on staging: https://deploy-preview-5083--sourcegraph.netlify.app/get-started

**Comment by marybelzer** [comment]
QA doc has been populated with feedback: https://docs.google.com/document/d/1aDTJ05CCczhWEwt-QNEHm-qnEbsY7qcVUmN_k--1BME/edit#

**Comment by mgyorffy** [comment]
ready for review: https://deploy-preview-5083--sourcegraph.netlify.app/

**Comment by marybelzer** [comment]
@mgyorffy Marketing noticed some of the text in the meta data is still missing:

Currently reads "Search across your repositories and the open-source universe."

Should say:

> Search across your repositories and the open-source universe with Sourcegraph Cloud. No technical setup is required. Sign up for free.
