### ISSUE TITLE
Remove "Free stickers" CTA on site footer

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5091]
Remove Free stickers link on the footer of the about site: https://about.sourcegraph.com/#:~:text=Sourcegraph%20overview%20(PDF)-,Free%20stickers!,-RESOURCES

**Comment by mgyorffy** [comment]
Ready for review on staging: https://deploy-preview-5094--sourcegraph.netlify.app/

**Comment by marybelzer** [comment]
Changes are approved by marketing - but the same bug seen in the staging link for #5092 exists here too (when you click "Dev tools quiz", it doesn't expand to the full screen landing page - it's kind of squished between the header and footer). Other than that - this is ready to go live.
