### ISSUE TITLE
Change Big code survey CTA --> Dev tools quiz on footer

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5092]
Change "[Big code survey](https://about.sourcegraph.com/#:~:text=Podcast-,Big%20code%20survey,-Community)" to say "Dev tools quiz".  New Destination: about.sourcegraph.com/dev-tools-quiz

**Comment by mgyorffy** [comment]
Ready for review on staging: https://deploy-preview-5094--sourcegraph.netlify.app/

**Comment by marybelzer** [comment]
@mgyorffy On the staging link, the quiz is kind of squished (see screen shot) - is this a symptom of the staging environment?

<img width="1292" alt="Screen Shot 2022-01-25 at 10 45 07 AM" src="https://user-images.githubusercontent.com/73856596/151039623-87fd34f6-a87f-4a37-b249-b9683d8718a2.png">
