### ISSUE TITLE
Design input for Anyscale logo and quote

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5093]
We are looking for some design input for #5071 

The request is to add a logo and quote to the top of the [cloud beta page](https://about.sourcegraph.com/cloud-beta/), but the requestor didn't have a super specific design in mind. Mate (who will be working on the code changes) called out screen real estate on smaller screen sizes, so looking for your expertise.

You can see more context in the conversation in the [Asana card](https://app.asana.com/0/1200095757619647/1201634832121942/f) (had some activity happen here before fully moving over to Github projects, sorry for the two systems!)

**Comment by stephzabala** [comment]
@marybelzer What about using one of the modules (ex. "Find and fix security vulnerabilities") from the use cases page, which allows for explanatory text on the left, and a quote on the right? https://about.sourcegraph.com/use-cases 

It would make more sense to me to add in a module than to add the logo/quote to the top of the page. It would be too crammed from a design/build perspective, but also overwhelming from a UX perspective.

**Comment by stephzabala** [comment]
If this doesn't work I can search for other options.

**Comment by marybelzer** [comment]
@stephzabala that sounds like it would work to me! I will propose that and let you know what I hear back.
