### ISSUE TITLE
CloseFactor (previously Fast Start) Social Design

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5106]
We need design and dev support to launch a target social campaign early in FY23. The scope includes: design a page template and produce four landing pages.

- Figma File (link when ready)
- [Copy doc including outline](https://docs.google.com/document/d/1xczYELbgcxrbubwHmW61BD4AOx0CcUou5vXIGIRZ-XM/edit)

Marketing has asked us to set a delivery date based on our current workload, and they are planning on two design reviews. @stephzabala can you put an estimated timeline in the comments and I will update expectations with Marketing? This is not an urgent request, just want to give them an estimate with your other work in mind. Thanks!

[Asana Card](https://app.asana.com/0/1200095757619647/1201745821158096/f)

Schedule:

- [ ]  Draft 2021-10-02
- [ ] First review 2021-18-02

**Comment by fabicastp** [comment]
Thank you, Mary and Steph! We're looking for a very simple design, similar to https://info.sourcegraph.com/demo-request - I don't expect more than one round of review. 

The request isn't urgent but we would like to launch this as early on Q1 as possible :) Thank you!!

**Comment by marybelzer** [comment]
This will be handled by Grafik

**Comment by marybelzer** [comment]
@bretthayes We are seeing an error where the page is just stuck on loading for some folks. One of our stakeholders contacted Chilipiper support, who said this in response:

> This almost always indicates that our code is on the page twice. I inspected the page and do see it on there twice, can you remove one version?

Can you take a look? Thanks!

**Comment by bretthayes** [comment]
@marybelzer yes for sure! I suspect I know what the problem is. I'll take a look asap!
