### ISSUE TITLE
CloseFactor Social [previously Fast Start Social] Template & Page Builds

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5107]
The scope includes: design a page template and produce two landing pages.

- The two pages, copy and outline can be found [here](https://docs.google.com/document/d/1xczYELbgcxrbubwHmW61BD4AOx0CcUou5vXIGIRZ-XM/edit).

- [Meta doc](https://docs.google.com/spreadsheets/d/1gVDNcoHrwE0Zw7UTG8fxu_z9Z8wPTSfROdBPtMyAJnQ/edit#gid=65555592)
- [Designs in Figma](https://www.figma.com/file/eKCQqJqFkbCJ6zhAheX5XJ/22_0224_SG_Close-Factor-Pages?node-id=0%3A1)
- Email submission box is via Chili Piper, documentation [here](https://help.chilipiper.com/hc/en-us/articles/360053798493)
- Dev Onboarding video : https://www.youtube.com/watch?v=DgwvhRW1Cbc
- Fixing vulns video: https://www.youtube.com/watch?v=13OqKPXqZXo&feature=youtu.be

**Comment by marybelzer** [comment]
Finalized! Ready to begin work.

**Comment by bretthayes** [comment]
@marybelzer Is the "Let's talk" email form a Chilipepper form? Do we have an embed code for this?

**Comment by marybelzer** [comment]
@bretthayes Tracking that down now. Heads up: This launch is blocked until we launch Code Insights (or lift the embargo), will let you know if that changes.

**Comment by marybelzer** [comment]
@bretthayes Yes, it's a Chilipiper box, just added a link to the documentation in the description. Let me know if there is any thing else needed!

**Comment by bretthayes** [comment]
> @bretthayes Yes, it's a Chilipiper box, just added a link to the documentation in the description. Let me know if there is any thing else needed!

I don't have access to HubSpot or Chilipepper. Did someone already create a form on either platform or am I supposed to? I'll need an embed code for the form if a form has already been created.

**Comment by marybelzer** [comment]
@bretthayes got some clarity here, we will be provided an embed code, will drop that here as soon as I have it but it may be a day or two.

**Comment by bretthayes** [comment]
Sounds good, thanks for tracking that down @marybelzer!

**Comment by marybelzer** [comment]
@bretthayes let me know if this does it!

Fixing vulnerabilities
```

<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "2762526",
	formId: "721ac3eb-d213-45b1-858a-2df8743ad143"
});
</script>
```

Dev Onboarding

```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "2762526",
	formId: "98187d3b-d8a9-43e2-bb95-d93dd029c688"
});
</script>
```

**Comment by bretthayes** [comment]
Thanks @marybelzer! They're integrated now, however, to match the designs, the forms will need to be styled and modified in HubSpot which I don't have access to. Otherwise, I'll need to do some gnarly style overrides.

**Comment by marybelzer** [comment]
@bretthayes someone with Hubspot access on the marketing side (likely whoever provided us these embed codes) will take care of it.

**Comment by bretthayes** [comment]
Sounds good, thanks @marybelzer!

**Comment by marybelzer** [comment]
@bretthayes I'm having trouble getting to this specific page in the preview link, adding the slug directly to the preview URL 404s - what's the best way to see the actual page(s)?

**Comment by marybelzer** [comment]
marketing went ahead and styled those forms, they're not exactly as they were in the designs but they're as close as they could get them

**Comment by marybelzer** [comment]
QA doc for this page, QA will close at 5pm PT today!

https://docs.google.com/document/d/1eWDBYQ84Lli3sngbBnmPjcF54VZaiPMlZKk6y5StH3M/edit

**Comment by marybelzer** [comment]
We should see the chilipiper form pop up after a user enters their email and clicks "let's talk", but the chilipiper form isn't currently prompting as referenced in [this thread](https://sourcegraph.slack.com/archives/C030TQC9PAS/p1647363450579679)
