### ISSUE TITLE
Break points in get started flow

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5118]
[This Slack thread](https://sourcegraph.slack.com/archives/C02HL0RNTGV/p1644204976234379) resurfaced an issue that came up in the get started flow discussions a while back. Mate adjusted the size of these boxes to help a bit, but it's still a lot of white space on some screen sizes:
![image (2)](https://user-images.githubusercontent.com/73856596/152828599-e7b0c2b9-875a-4a8c-be5b-2b4798571768.png)

Looking for design input on how we should handle this and we can then have an engineer adjust the page. Thanks!

**Comment by Joelkw** [comment]
Opening, this was not supposed to close – #5140 was a quick partial fix.
