### ISSUE TITLE
Code Insights demo page

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5141]
- Same[ ](https://about.sourcegraph.com/contact/request-batch-changes-demo)style of [Batch Changes demo page ](https://about.sourcegraph.com/contact/request-batch-changes-demo)
- Hubspot form attached (please remember to add ChiliPiper code). Copy:

> Connect with a product specialist from Sourcegraph to learn how Code Insights can help you track and visualize everything in your code, from migrations to code smells, in a seamless way. 

@katjuell Marketing would like to integrate ChiliPiper into the demo page. Here's the Asana task for when Mate did it on our other about pages: [✓ Chili Piper / Hubspot integration ](https://app.asana.com/0/1200095757619647/1201620993675357)- is this possible to have before launch? Hoping we can reuse some of that code? It's definitely preferred to have on the launch date but it's not a blocker.

Meta: https://docs.google.com/spreadsheets/d/11DYIN1e6-weZ0Rb9-_bmnx1Uje8fs2mVoQUUdjjYBqk/edit#gid=572619067

**Comment by katjuell** [comment]
Awesome! @marybelzer This should be doable. I'll just need these pieces of info:
```
portalId,
formId,
targetId,
```
And I am assuming that other folks will be setting up the form in HubSpot?

**Comment by marybelzer** [comment]
Hubspot form embed code:


<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
 hbspt.forms.create({
 region: "na1",
 portalId: "2762526",
 formId: "a58be17d-86ad-4a6e-8c97-83818aafd2ab"
});
</script>

**Comment by marybelzer** [comment]
@katjuell I found this for targetid on the [batch changes page](https://github.com/sourcegraph/about/blob/main/website/src/pages/contact/request-batch-changes-demo.tsx):
![image](https://user-images.githubusercontent.com/73856596/154364464-64f8f49a-b0cc-4e45-ba79-da0367fe2071.png)

**Comment by marybelzer** [comment]
Copy added to description

**Comment by katjuell** [comment]
Closed in #5148
