### ISSUE TITLE
Install Drift JavaScript code on the about site

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5142]
- [Documentation](https://gethelp.drift.com/hc/en-us/articles/360019349154-Install-Drift-on-Your-Website-Using-the-Javascript-Snippet)

**Comment by bretthayes** [comment]
@marybelzer will need access to Drift in order to grab [the unique code snippet](https://gethelp.drift.com/hc/en-us/articles/360019349154-Install-Drift-on-Your-Website-Using-the-Javascript-Snippet#:~:text=Your%20Drift%20account%20has%20a%20unique%20and%20personalized%20snippet) or I need the snippet provided to me if that's out of scope for my access.

**Comment by marybelzer** [comment]
@bretthayes Pasted below what I _think_ you need. Greg Bouton has also added his drift login to the sourcegraph shared 1password account so you can find it there if you need to log in. Let me know if that does it!


<script>
"use strict";

!function() {
  var t = window.driftt = window.drift = window.driftt || [];
  if (!t.init) {
    if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
    t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
    t.factory = function(e) {
      return function() {
        var n = Array.prototype.slice.call(arguments);
        return n.unshift(e), t.push(n), t;
      };
    }, t.methods.forEach(function(e) {
      t[e] = t.factory(e);
    }), t.load = function(t) {
      var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
      o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
      var i = document.getElementsByTagName("script")[0];
      i.parentNode.insertBefore(o, i);
    };
  }
}();
drift.SNIPPET_VERSION = '0.3.1';
drift.load('bgv3pp29xsp9');
</script>
