### ISSUE TITLE
Webinar landing page

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5146]
Opening this tasks to kick-off the webinars landing page development 

Resources

- [Design](https://drive.google.com/drive/folders/15e9mwdnsM6hLZGSHSvHS8RZsYV7U-9h0)
- [Folder with creative assets](https://folder%20with%20creative%20assets/) (svg)

What's missing from Marketing: 

- Webinar page meta
- Guests photos → use[ this template ](https://www.figma.com/file/bVhtFBhWTVHc7iYfHRColC/SG-Webinar-Presenter-Photo-Template-(1))and save the image as svg
- Demio registration form embed code 
- Copy

**Comment by bretthayes** [comment]
Closing this in lieu of our new templates for guides and webinars.
