### ISSUE TITLE
Sourcegraph Cloud Early Access page updates

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5166]
Sourcegraph Cloud will move from "Private Beta" to "Open Beta" this quarter, likely in April. At that time, we would like to update the /cloud-beta page on the About site to reflect this change. It would need some small copy changes, and would need links to point to a new onboarding flow rather than links to the current waitlist request form.

It will be time sensitive to align with the move to Open Beta, but that date is not yet determined. We are projecting mid April

**Comment by marybelzer** [comment]
NOTES FROM KICKOFF

- April 14, will go to "early access". Will no longer be gated by a form. Instead of "join a waitlist", will be something like "create an organization"
- Evolution of existing page
- Update URL to /cloud-early-access
- Minor copy changes to get started flow - currently says beta

**Comment by elzannewentzel** [comment]
Landing page
🔗[Meta](https://docs.google.com/spreadsheets/d/1rLOe6FuVUZJzPPM0FubbmYn5IHwAUB77ZbQJzVwn1Ys/edit#gid=0) → notice new URL 
We won't need to create a redirect per [this comment thread](https://app.asana.com/0/0/1201902705226577/1202020907438539/f)
👁️ Main CTA direct to sourcegraph.com/search
[🔗Figma file ](https://www.figma.com/file/prV5OGh07RM1Slap2zLr11/Cloud_BetaLanding?node-id=61%3A794)
📁Creative assets 

Additional updates to about
[🔗Copy doc](https://docs.google.com/document/d/1h-6uiOUj4SD5F8q1pmuGFIq3Q9_BoVeK9QVTXI6ZjnI/edit#)

Launch: April 21
