### ISSUE TITLE
Update Unity logo

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5170]
Unity updated its brand assets. Please update the logo in our carousel.

New logo here: https://brandguide.brandfolder.com/unity/downloadbrandassets

**Comment by bretthayes** [comment]
@marybelzer looks like we are already using the latest `U_Logo_Black_RGB.svg` in their brand assets which is from `10/7/2021`. Is there something I'm missing here or another specific logo we want to use?

**Comment by marybelzer** [comment]
@bretthayes I will follow up with marketing, this request came in about a week ago so I'm wondering if they received this info via email and it's not updated on that link yet, maybe? stand by, will update you asap!

**Comment by bretthayes** [comment]
Sounds good, thanks! @marybelzer

**Comment by marybelzer** [comment]
We aren't hearing back from Unity on this, so I'm going to close this as "cancelled" for now. Marketing will submit a new request if we do get the proper logo at some point.
