### ISSUE TITLE
Fixing Vulnerabilities Landing Page

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5172]
Note: Nutanix's quote won't link to a case study, not live yet

The [Figma file](https://www.figma.com/file/aA1cNEm2JWtBSuijZyxROs/Use-Case-Template?node-id=0%3A1) is the source of truth for copy and design

🔗Figma file → WIP tab, look for V2
🔗[Meta](https://docs.google.com/spreadsheets/d/1_mZxd_RLysQ0VMUzHK_gQZ8Jak-o7cTyaWS8tqYLZvg/edit#gid=149103332)
🔗[Creative files](https://drive.google.com/drive/folders/1_TpGTK2bt9NJ6PSBSaMab67q_zgkVHj0)

CTAs

- Request a demo: https://info.sourcegraph.com/demo-request
- Try Sourcegraph: https://about.sourcegraph.com/get-started
- Log4j was the tip of the iceberg / Read the blog post: https://about.sourcegraph.com/blog/log4j-log4shell-0-day/
- Source: Security intelligence: https://securityintelligence.com/news/news-vulnerabilities-25-days-remediate/
- Code Search: https://about.sourcegraph.com/code-search/
- Batch Changes: https://about.sourcegraph.com/batch-changes/
- Code Monitoring: https://docs.sourcegraph.com/code_monitoring
- Clodflare case study: https://about.sourcegraph.com/case-studies/cloudflare-accelerates-debugging-and-improves-security
- Indeed case study: https://about.sourcegraph.com/case-studies/indeed-accelerates-development-velocity
- Explore other use cases: https://about.sourcegraph.com/use-cases/
- Log4j Log4Shell 0-day: find, fix, and track affected code: https://about.sourcegraph.com/blog/log4j-log4shell-0-day/
- The Nine Circles of Dependency Hell (and a roadmap out): https://about.sourcegraph.com/blog/nine-circles-of-dependency-hell/
- How to remove secrets from your codebase: https://about.sourcegraph.com/blog/eliminate-secrets-from-codebase-with-universal-code-search/
- Ready to get started? https://about.sourcegraph.com/get-started

**Comment by katjuell** [comment]
@marybelzer are we linking to this page from the `use-cases` index hero only?
![Screen Shot 2022-03-14 at 12 58 59 PM](https://user-images.githubusercontent.com/43454804/158442808-dcdfdad5-01d1-4f33-9355-47d3435bd9d2.png)

Or also from the body section on the index page?
![Screen Shot 2022-03-14 at 12 59 08 PM](https://user-images.githubusercontent.com/43454804/158442861-ca07d5b4-3111-4434-a1fc-49524aae7e1f.png)

**Comment by marybelzer** [comment]
@katjuell yes, no need to change existing links on the use-cases page. however, they would like to add a "learn more" link next to "request a demo" that would take the user to this new page - I have asked for them to add this into the Figma to keep that our source of truth for designs

**Comment by katjuell** [comment]
Sweet! Tyvm!

**Comment by marybelzer** [comment]
@katjuell mock up added to figma [here](https://www.figma.com/file/aA1cNEm2JWtBSuijZyxROs/Fixing-vulnerabilities-page?node-id=315%3A36)

Fabiana put this together, styles don't match exactly in her example here, we should probably match font size to the existing demo button. Let me know if you need anything else!

**Comment by katjuell** [comment]
Awesome! Tyvm!
