### ISSUE TITLE
Add MercadoLibre logo

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5173]
Add MercadoLibre logo to our carousel. 

Location: Where the Apex logo is. We can move the Apex logo to the back of the carousel of have it next to MercadoLibre. Whatever is easier. 
![mercadolibre](https://user-images.githubusercontent.com/73856596/156242268-f32c4830-928d-426e-aeaa-1af1e68dacd6.svg)

**Comment by marybelzer** [comment]
@bretthayes Just got this request in, not urgent, but curious if it makes sense to tackle while working on #5170 ?

**Comment by bretthayes** [comment]
@marybelzer for sure! I'll add this in when I tackle #5170
