### ISSUE TITLE
Gated page: Optimizing developer onboarding

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5206]
The Demand Gen team requested a gated landing page for the developer onboarding use case. The landing page will use a new template that we can continue to reuse in the future for guide related pages. 

[🔗Meta](https://docs.google.com/spreadsheets/d/1VqW_U3RT1Vx-t7PksgwOadXsOaUTwGYvUnqRnN-fmb4/edit#gid=1572625403)
[🔗Figma ](https://www.figma.com/file/EVthdgOQ059ZS8S4Ixx91v/Optimizing-dev-onboarding)
PDF guide: attached
[Optimizing developer onboarding.pdf](https://github.com/sourcegraph/about/files/8699613/Optimizing.developer.onboarding.pdf)

Hubspot form →❗Don't include ChiliPiper → The form leads to the guide. 

```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
 hbspt.forms.create({
 region: "na1",
 portalId: "2762526",
 formId: "af3bc75e-c4f0-43e7-9829-c1d5d59e0a56"
});
</script>
```

**Comment by zlonko** [comment]
Because our repo merge is imminent, this issue will be developed in Next as opposed to the usual Gatbsy --> Next workflow.

**Comment by zlonko** [comment]
Awaiting our merge prior to opening the PR. Otherwise this is ready for eng review 👍 @elzannewentzel
