### ISSUE TITLE
Add /guides section

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5234]
**PAUSED**: Demand gen will provide a new request for this work.

The Demand gen team want to add a /guides section to the About site to give recent gated content assets a permanent home on the marketing site.

Requirements can be found [here](https://docs.google.com/document/d/1O-xMHFhoAqRPf6twGolufkdRbpcb85kBZw-jwhFu6VM/edit)

This is not a blocker to anything, but we do have several more guides slated for publication soon

Asana card: https://app.asana.com/0/1200095757619647/1202058387310661/f

**Comment by bretthayes** [comment]
Closing this in lieu of the new resources page #5651
