### ISSUE TITLE
Code Reuse Landing Page

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5239]
Create a new landing page for the Code Reuse use case.

[🔗Code reuse meta](https://docs.google.com/spreadsheets/d/1YRjNjmcG5ACNiFyF94yZ6OTexo1TpfCbK5BKHwtCWyg/edit?usp=sharing)
🔗[Figma file](https://www.figma.com/file/kQTq5eWvjbMcMmsvZ8wvyF/Code-reuse)

Asana card: https://app.asana.com/0/1200095757619647/1201875233104236/f

**Comment by elzannewentzel** [comment]
@st0nebraker Please note the update on the CTA's position in the Figma file

**Comment by st0nebraker** [comment]
[QA feedback doc](https://docs.google.com/document/d/1WBSbUjN5oWk9fRIH61uP0HjHqrfTLCQ_t1tDhI3OIBs/edit#)
