### ISSUE TITLE
Add incident response policy to /security page

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/about#524]
I.e., what happens if we discover a vulnerability

Feel free to assign someone else

**Comment by beyang** [comment]
@nicksnyder this related to the recent changes you've been making to our security reporting docs and policy?

**Comment by dadlerj** [comment]
Not urgent, but it's something that comes up in many of the vendor security form reviews I do, and it's nice to be able to point to a documented policy.

Putting this into the handbook would also be perfectly fine.

**Comment by nicksnyder** [comment]
I haven't changed anything with our policy (just consolidated docs), but I agree this part should be explicitly documented in our source of truth document: https://about.sourcegraph.com/security
