### ISSUE TITLE
Continuous onboarding guide / Non-blocking feedback

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5240]
We launched the [continuous onboarding guide](https://about.sourcegraph.com/guides/continuous-developer-onboarding/) and received non-blocking feedback to implement. 
The feedback doc: https://docs.google.com/document/d/1ILVf3-_H0BHEpBOxTAQ5_tifuG2wW1JjX1Jz3bEeDc0/edit

**Comment by zlonko** [comment]
Looking at this again after deploying #5231. Because the layouts are quite similar, it seems that the scope of this issue may end up applicable to both. I am going to unassign for now so that we can discuss scope.
