### ISSUE TITLE
Update images on the Jobs page

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5241]
We’re using a hero image on our Careers page featuring a teammate who is no longer with the company.
Please swap the web and mobile image of the Careers page (https://about.sourcegraph.com/jobs) with these images: https://drive.google.com/drive/folders/1RwhRMvLWIQfQjwKtSQNqvIa1MUTGZcBD?usp=sharing

Requested by the Community and People Ops teams. 
Urgency: This is urgent for them and we should plan this into our next sprint to be done as soon as possible.

**Comment by bretthayes** [comment]
Adding a ticket to our replatform so this isn't left behind.
