### ISSUE TITLE
Remove and redirect /cloud-beta page

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5264]
We are pausing the Cloud SaaS for Teams on Sourcegraph.com launch and need to update two pages and then take down the cloud-beta page.

**Context**
We believe that pausing work on Cloud SaaS for teams on Sourcegraph.com is necessary to focus on building for our target market for FY23 and beyond (Strategic, Enterprise, Commercial Growth). The support and security risks of adding more teams to Cloud SaaS outweighs the benefit of the limited trial environment it provides.  We need to be laser-focused on enabling Sourcegraph managed trial and production deployment and administration for enterprises.

**Includes**
1)Update copy on [/get-started](https://about.sourcegraph.com/get-started/) and /[get-started/cloud](https://about.sourcegraph.com/get-started/cloud) [see screenshot attached] 
![CleanShot 2022-04-19 at 14 16 59@2x](https://user-images.githubusercontent.com/88658267/164452009-0a5d26f3-f67a-4394-8f7d-5d3f2b0e541b.png)

After completing item 1:
2)Take down the /cloud-beta page and redirect the URL to our About homepage temporarily.

Asana: https://app.asana.com/0/1200095757619647/1202142467535925/f

**Comment by zlonko** [comment]
@elzannewentzel Adding a note that /cloud-beta was recently ported over in https://github.com/sourcegraph/about-replatform/issues/85, for when we open a ticket that applies these steps to the Replatform.
