### ISSUE TITLE
Navigation updates: main nav, footer & vulnerabilities page

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5266]
The Demand Gen team requested updates to the customers dropdown in the main navigation, the footer and links on the Use Cases landing page and the Fixing vulnerabilities page.

**Note**: please refer to this [doc](https://docs.google.com/document/d/1WWlrDoND2-YC1n1P81JDhFW3fJQ2tKP4THqt3MLiuuQ/edit#) for the requirements.

**Comment by zlonko** [comment]
This is paused pending discussion in the doc on removals and renamings.
