### ISSUE TITLE
Non-blocking feedback for Incident Response Use Case Page

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5287]
Implement the non-blocking feedback for the Incident Response page.
https://docs.google.com/document/d/18dNP6QihejP8CVSm-tdmbH20D5beFYlGXyBme0286U4/edit#

**Comment by zlonko** [comment]
The PR is still ready, but I am moving to paused so we can plan to include with the other non-blocking feedback for Use Case pages in next sprint as mentioned.
