### ISSUE TITLE
Non-blocking feedback for Podcast sponsorship page

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5289]
Implement the non-blocking feedback for the Podcast sponsorship page.
https://docs.google.com/document/d/1Zku5LzvM13wldWWB0Rj4d3KKkdi5QHteqsQOZVj1fkc/edit

**Comment by st0nebraker** [comment]
Closing as the non-blocking feedback is for a `sourcegraph.com` addition, outside of CPT's domain
