### ISSUE TITLE
Form loading issues

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5304]
Andy in Demand Gen team reported that the form on the CI page is only loading +/- 50% of the time for him. He reported that it's intermittent, and not to do with clicking the back button. 
<img width="839" alt="image (1)" src="https://user-images.githubusercontent.com/88658267/165795761-cc81279e-8513-431b-87b4-5fa7ab41679e.png">
<img width="1299" alt="image (2)" src="https://user-images.githubusercontent.com/88658267/165795919-767b2506-83a4-4804-8ef7-d5caf88ec81e.png">

.

**Comment by elzannewentzel** [comment]
The problem is on pages with two forms, delay in loading comes from double form. onFormReady method firing twice. Hubspot does not support this and we would need to work out a solution to support this.

**Comment by bretthayes** [comment]
This is fixed now
