### ISSUE TITLE
Blog post: announce the initial release of scip-python

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5312]
The Code Intel team are writing a blog post to announce the initial release of scip-python, a new LSIF indexer that enables precise code intelligence for Python.

> The target audience of this blog post is all Sourcegraph customers that are using Python. This announcement is exciting because Python is one of the most widely used programming languages among Sourcegraph customers and we have never supported precise code intel for Python. The repo is https://github.com/sourcegraph/lsif-python but we have not started drafting this blog post. We expect the structure will roughly use a similar structure as the lsif-typescript announcement.

- Create a new blog post, @tjdevries / @olafurpg  will provide the blog copy and desired URL
- Add the post to the blog index page

**Release note**: All 4 blog posts should be released simultaneously.
https://github.com/sourcegraph/about/issues/5311
https://github.com/sourcegraph/about/issues/5313
https://github.com/sourcegraph/about/issues/5336

**Comment by tjdevries** [comment]
blog post: https://docs.google.com/document/d/1Q78Jok87g0ogKjO26cPnEMrqAgWe0ULNi499AiWBIsA/edit#

**Comment by tjdevries** [comment]
(we changed our minds about how we wanted to the blog post, will update with new link and information in the next few days)

**Comment by tjdevries** [comment]
Released
