### ISSUE TITLE
Demand Generation: Dev Onboarding landing page

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5320]
This is a new landing page for the Dev Onboarding use case. The page is not linked from anywhere in the about.sourcegraph.com platform.

🔗[Meta](https://docs.google.com/spreadsheets/d/1JCCIqbP9V6Q4Vwc4yEBJc1wX3y-BHUx32naWRWswWhw/edit#gid=1572625403)
🔗[Figma file](https://www.figma.com/file/hTjBMaMgCKlkO6OOOThU6r/Dev-Onboarding-DG-landing-page?node-id=0%3A1)

**Comment by zlonko** [comment]
This issue will not be ready for development in this sprint. The status has been updated to paused.
