### ISSUE TITLE
Homepage: add data attributes to CTAs

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5331]
There are CTA's on the homepage that needs the data-button-style, data-button-location and data-button-type attributes added.

**On the homepage, for the use cases section:** 
Add the attributes to the 5 “Learn more about… ” CTA’s  

**On the homepage, under the 1.2M engineers heading:** 
Add the attributes to the “Learn how our customers use Sourcegraph” CTA

**Comment by bretthayes** [comment]
@elzannewentzel I updated our [Tracking doc](https://docs.google.com/document/d/1Q1JMzyRmwNKk65KxxtT9EOnxoSf2dHEGkUAPbJkKzI4/edit#) to reflect these updates.
