### ISSUE TITLE
Blog thumbnails on use case pages

### ISSUE THREAD

**Issue by zlonko** [sourcegraph/about#5337]
Arrays for `BlogListItems` were updated in #5271, but not on the Incident Response and Code Health Use Case pages. This caused the thumbnails for blog items not to render. This updates the array from `{...image}` to the new structure, `{...img:{src,alt}}`.

**Comment by bretthayes** [comment]
Thanks for catching this @zlonko!! I saw this in one of my merge fixes in sourcegraph/about-replatform#144
