### ISSUE TITLE
Add code syntax highlighting support for Markdown

### ISSUE THREAD

**Issue by katjuell** [sourcegraph/about#5382]
Add multi-language syntax highlighting support for code blocks that use the `<code>` element. Work with Brand to come up with a theme or a set of syntax highlighting colours that we can use.

[This page](https://about.sourcegraph.com/blog/introducing-migrator-service/) is an example that includes a few code blocks but the colours are too bright. View [this thread](https://sourcegraph.slack.com/archives/C015P61EXV1/p1649322816496449) for context.

**Comment by st0nebraker** [comment]
Closed in [PR#5520](https://github.com/sourcegraph/about/pull/5520)
