### ISSUE TITLE
Mobile: improve first-time visit experience

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5430]
On mobile, the first time visit is not such a great experience.

1. The cookie banner is taking up a LOT of vertical space, more than half the screen, occluding the homepage.
2. The bot’s speech bubble is occluding the cookie banner’s buttons. The (x) in the close button is not centered and the red :one: seems stressful (IDK what a better word to describe the feeling is, but the (1) is asking for attention even though it is far from the most important thing on the page).
3. The visual spacing in the Sourcegraph text + logo near the top seems a bit too narrow. (Maybe that’s just how the logo is, I’m not sure, but it looks a little visually cramped given that other things are more spaced out.)

Reported in #[feedback-dogfood](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1654502616562439)

1. Increase logo size
2. Fix the bot at the top 
3. Reduce cookie banner size

![Image](https://user-images.githubusercontent.com/59381432/172203671-363f989c-24dc-4794-a053-c56b20c1d11c.png)

**Comment by st0nebraker** [comment]
> 2. Fix the bot at the top

Can you clarify this acceptance criteria point @elzannewentzel ? Where do we want the chat bot to go on mobile?

**Comment by elzannewentzel** [comment]
@traceyljohnson Can you advise please? :)

**Comment by traceyljohnson** [comment]
@st0nebraker @elzannewentzel Correct me if I'm off, but ideally, we'd only be giving the user one "task" at a time, right? If possible, could we delay the bot's appearance until the user has accepted cookies? If that isn't possible, then I think having the cookie banner pinned to the center of the screen (leaving room for the chatbot below) makes sense. 

Plus these edits: 
1. Reduce cookie headline by 20% so it fits on one line with emoji
2. Increase logo size to 32px height (will match the navbar logo dimensions in the DLS) 
3. Ensure the navbar spans the width of the rest of the page's content (appears to have 32px padding on both sides vs the 16px standard)

Bonus:
Could we also reduce the whitespace between the H1 and navbar to 64px? Feels like a lot atm.

**Comment by st0nebraker** [comment]
Great! My fix has the cookie banner covering the chat bot until the cookie banner is taken care of. I couldn't reproduce the large cookie banner text, it looked good on every android I tested, but the other changes are in [this PR](https://github.com/sourcegraph/about/pull/5495) & can be viewed on the staging link [here](https://deploy-preview-5495--sourcegraph.netlify.app/).



![Image](https://user-images.githubusercontent.com/59381432/174375927-ec582411-7e67-46d3-a390-2eb509fd6ebb.png)

**Comment by traceyljohnson** [comment]
Overall, this is an improvement! However, now that the cookie banner is at the bottom, the main hero's buttons are visible above, causing a disorienting amount of buttons to be faced with 😅 . I'm wondering if we can have it covering those again? If not, as I said, this is an improvement over the "noise" of the chatbot and cookie banner.

**Comment by st0nebraker** [comment]
I agree, I can get it to cover most of the screen just on mobile + tablet. I think this looks better, but still shows our logo + navbar. What do you think? @traceyljohnson 


![Image](https://user-images.githubusercontent.com/59381432/174681447-368a9c92-eedf-4c12-853e-053e5074dfdb.png)

**Comment by st0nebraker** [comment]
Can you give this a final look when you have a moment, @traceyljohnson ? Staging link [here](https://deploy-preview-5495--sourcegraph.netlify.app/).
