### ISSUE TITLE
Make .md tables mobile friendly

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/about#5454]
Following up this quick bug fix: [#5453](https://github.com/sourcegraph/about/pull/5453), audit and ensure all other tables used for Marketing articles (`.md`s), are mobile friendly

**Comment by zlonko** [comment]
Documenting here that https://github.com/sourcegraph/about/issues/5457 may be a good solution for this! A gray box seems to appear on full view of the table with `overflowX: scroll`. With `overflowX: auto`, the gray box is removed on full view, and a gray bar appears for horizontal scrolling on mobile.
