### ISSUE TITLE
Horizontal scroll bug on SCIP-TS blogpost

### ISSUE THREAD

**Issue by zlonko** [sourcegraph/about#5457]
A gray box appears beneath the blogpost's table when the entire table is visible. 

An `overflowX: scroll` was added in https://github.com/sourcegraph/about/pull/5453. If `overflowX: auto` is used instead, the gray bar will not appear and the table will still be horizontally scrollable on mobile.

**Comment by bretthayes** [comment]
We may want to always keep the scrollbar to show the intent that the table is scrollable for UX purposes. Some non tech savvy users might think it's a bug. 😬  Thoughts?

**Comment by bretthayes** [comment]
@zlonko We may want to always keep the scrollbar to show the intent that the table is scrollable for UX purposes. Some non tech savvy users might think it's a bug. 😬  Thoughts?

**Comment by zlonko** [comment]
@bretthayes Sorry, I did not catch this note before opening the PR. I agree that the scrollbar should be visible to communicate this intent. However, I noticed that a gray box (which does not look like a scroll bar) appears beneath the table when it is fully visible now. It is not interactive and to me appears like a bug. When I tested the solution, the scroll bar still appears on mobile as before. Happy to know your thoughts, and if you prefer a different solution.

<img width="755" alt="Screen Shot 2022-06-08 at 4 56 21 PM" src="https://user-images.githubusercontent.com/60713139/172725916-8ba3c4d5-7c55-44dc-a018-5c460baff7af.png">

**Comment by bretthayes** [comment]
Ha! You're quick! 😉  I actually deleted my comment before you responded haha because I realized that it appears on desktop and mobile. I think what you have in your PR is the best solution since it will show on mobile but not desktop. ✨
