### ISSUE TITLE
Validate user flow data

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5461]
Stakeholder: Marketing strategy & analytics 

As part of the recently formed marketing tracking working group, we want to make sure that we know analytics is working correctly on the about. sourcegraph.com platform. 

To support this, we need to validate that we don't lose information on the user that starts on about site, goes to /search, and comes back to about site to submit form.

Related Slack thread: https://sourcegraph.slack.com/archives/C03KB4WKJRW/p1654726472287969

**Comment by bretthayes** [comment]
I can confirm that with cookies cleared and reset, visiting `sourcegraph.com/search` creates a cookie with `sourcegraphAnonymousUid` and it can be read on `about.sourcegraph.com`. This data is submitted to HubSpot for all forms. The hidden form field that captures and populates this data is called `anonymous_user_id`. You can see this in our [HubSpot hook](https://github.com/sourcegraph/about/blob/main/src/hooks/hubSpot.ts#L132-L133). You can view the form submissions under `Lead Capture>Forms` in HubSpot for any form and the Anonymous User ID will be the same.

Screenshots below are from my tests:

![Screen Shot 2022-06-13 at 5 15 38 PM](https://user-images.githubusercontent.com/1733936/173446921-260e403f-9d19-4600-9beb-178f9937119d.png)
![Screen Shot 2022-06-13 at 5 16 01 PM](https://user-images.githubusercontent.com/1733936/173446923-22016628-7a57-4ced-a9b5-fc41d1bc06e4.png)
![Screen Shot 2022-06-13 at 5 16 29 PM](https://user-images.githubusercontent.com/1733936/173446926-acd35e59-077d-458c-9f43-9629b64ea280.png)
