### ISSUE TITLE
Gated page: Fix & find vulnerabilities e-book

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5473]
Stakeholders: Nick, Fabiana
What? E-book to be promoted on paid campaign 
Why? Capture leads with engaging content 
The existing template for [guides]( https://about.sourcegraph.com/guides/continuous-developer-onboarding) can be reused for this.

🔗[Landing page copy](https://docs.google.com/document/d/1lOr2FynLaL2U3flzAuQzm3LNNzGpCANdWPtRFG2ozIA/edit)
[🔗Meta](https://docs.google.com/spreadsheets/d/1W_jBN-pSWJ0bURk9z7rtb4swvf-9H5urLe9Zj4k_XwQ/edit#gid=715450113) ✅
[How companies fix vulnerabilities Ebook.pdf](https://github.com/sourcegraph/about/files/8952123/How.companies.fix.vulnerabilities.Ebook.pdf)

Embed form: 
Add "Download the e-book"
Embed form: 
<script charset="utf-8" type="text/javascript" src="[//js.hsforms.net/forms/v2.js](https://sourcegraph.slack.com//js.hsforms.net/forms/v2.js)"></script>
<script>
  hbspt.forms.create({
    region: "na1",
    portalId: "2762526",
    formId: "610debf1-bbce-45d6-a492-6858b5b3db18"
  });
</script>

**Test form submission:**
1. Check HubSpot syntax #5409 
2. Check that form thank you message shows correct link to PDF
3. Check the email that is generated and that the links are correct

Asana: https://app.asana.com/0/1200095757619647/1202429370797707/f

**Comment by zlonko** [comment]
@bretthayes Looking for how you would prefer to align this considering #5483 is still Blocked/Paused. Shall we create this using the existing syntax and I can add a fix in #5483?

**Comment by bretthayes** [comment]
@zlonko feel free to continue as normal with the existing syntax so that #5483 doesn't block you. I can update any merge conflicts that come my way in that PR if this ticket is merged before then. I'm unsure of the timeline atm on #5483 given the recent circumstances.

**Comment by zlonko** [comment]
Right on, I'll continue with this as specified. Thanks, Brett!

**Comment by zlonko** [comment]
@bretthayes In case it can save you some time, I went ahead and opened #5507 to merge this new page and its updated syntax into the HubSpot Master Forms PR.
