### ISSUE TITLE
Add missing CTA tracking attributes

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5487]
Stakeholders: Adam G, Erica F, Rebecca R
What? In the CTA audit, we identified which CTAs don't have the 3 data attributes needed to track them in GA. These attributes need to be added to the identified CTAs and links.
Why? The Marketing Analytics team can get data for full views of each interaction because not all CTAs are set up and tagged correctly.

**Requirements:**
- In the [audit spreadsheet](https://docs.google.com/spreadsheets/d/1N4Bgt74f1XDV3B3bnn5rNT5XoV_2Jfl8Rfk5-WTYG38/edit#gid=0), rows with a grey background indicate which links/CTAs need attributes. Update these with the style, location and type attributes.
- Where applicable, also add the title to the links that do not have it. (this can be done in a separate task, the data attributes are more important)
- [Attribute definitions](https://docs.google.com/document/d/1Q1JMzyRmwNKk65KxxtT9EOnxoSf2dHEGkUAPbJkKzI4/edit#heading=h.k7nyndmxaz4x)
  - Additional attributes might be needed if our existing set does not cover it.  
  - We need to test this and confirm that we can see the correct CTA data attributes in GA

Might be useful: 
Pages with CTA attributes:https://k8s.sgdev.org/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/about%24+data-button-+&patternType=regexp
Code Insight: https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcyNjZ9

Related to: #5447

**Comment by bretthayes** [comment]
@st0nebraker I left a comment in the [requirements doc](https://docs.google.com/document/d/1Q1JMzyRmwNKk65KxxtT9EOnxoSf2dHEGkUAPbJkKzI4/edit) to change out our naming convention for these tracking attributes so they're more accurate.

Please take a look at [this comment thread](https://github.com/sourcegraph/about/pull/5555#discussion_r914873436) and the follow up ticket (#5557) that relates to this.

cc: @fabicastp

**Comment by st0nebraker** [comment]
Sounds good! I'll work on this task next week 😸 . Thanks for all the relevant context, @bretthayes . I'd like to wait until the new naming is in place to not do the work twice, but that might take some time. We can actually use Batch Changes for the name updates probably!
