### ISSUE TITLE
Investigate UTM params causing duplicate forms

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5488]
Stakeholder: Marek, Developer Education
What: The form duplication bug can be related to the UTM params added to an URL. 
Why? UTMs are an important part of tracking for marketing and the forms are important for lead generation. Both should be working without breaking the other. 

Report from Marek: https://sourcegraph.slack.com/archives/CNC4YAL1E/p1655328497294179

**Comment by jdorfman** [comment]
Confirmed thanks @bretthayes
