### ISSUE TITLE
Extend Video component for source prop

### ISSUE THREAD

**Issue by zlonko** [sourcegraph/about#5496]
Refactor `filePath` to `source` to allow for wider implementation (e.g., blogposts).

[Context from review](https://github.com/sourcegraph/about/pull/5493#discussion_r901846919)

Example: 
```
interface Video {
  source: {
    webm: string
    mp4: string
  }
  loop: boolean
  caption: string
  title: string
}
```

Also, please identify opportunities to cut the blog SCSS out into Bootstrap utility classes. ([Reference](https://github.com/sourcegraph/about/pull/5493#discussion_r901990248))

**Comment by zlonko** [comment]
It looks like component and interface were updated in https://github.com/sourcegraph/about/pull/5548. We can still use this issue to clean up the blog SCSS where possible!

**Comment by bretthayes** [comment]
The Video component updates were updated in #5493. Other styling initiatives will be tackled in #5381.
