### ISSUE TITLE
Resource page planning

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5532]
Stakeholders: Fabiana, Tracey, Andy, Nick 
What: Review the proposed layout for the new Resources page and plan the development tasks.
Why? The marketing team produces a lot of content but the marketing platform does not have the capability to present the content in one place for discoverability and consumption. There is no hard deadline for the release of this page, but we do need to provide a timeline.

🔗[Figma](https://www.figma.com/file/n3nHcRhzmipzlSj3WvqBqi/Resources-page?node-id=176%3A3625)
Scope document: https://docs.google.com/document/d/1U7up01mOG1EscbbbysCWPvYuTX336Zgo4-u5zGANOhg/edit#

Asana: https://app.asana.com/0/1200095757619647/1202519591393046/f

**Comment by st0nebraker** [comment]
Some of my thoughts:
- If not every blogpost will be a _Resource_ on this page, will that be confusing for the user? We have over 400 blog posts. Is there an extra tag we should give to blog resources to distinguish them from a regular blog post? This will be helpful on CPT side too so we know how to distinguish the data.
- With a new Resource hub page, will there still be indices for the sub-categories of content? (I.e `about.sourcegraph.com/blog`, `about.sourcegraph.com/podcast`. (Same question Tracey had [here](https://docs.google.com/document/d/1ZUpYZcHM9NAgU3krYnhZ18A8tvPbbhp-1Feo0-N2zZk/edit?disco=AAAAa3DLdZI)).
- If we are **not** preserving sub-category content indices, we'll need to re-design the navigation & footer links available.
- My instinct is that a CMS would be best to implement this, as mentioned before. To save us the work of reinventing the wheel. We'll get a lot more out of the box functionality supporting these features, as well. Additionally, it would help stakeholders become self-service to produce content quicker in the long run, **and** help reinforce our brand standardization. A lot of wins on a lot of fronts.
- Search functionality isn't part of iteration 1, but I am cautious what forethought we need to put into this when setting up our data. @bretthayes have you used search within a CMS before? Any cautionary tales or considerations we should mull over?
