### ISSUE TITLE
Increase blog post width

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5541]
Stakeholders: feedback from #dogfooding
What?: Look at increasing the width of a blog post. 
Why?: The width of the content area is too small and wastes white space that can be used to improve the layout of the content.

https://sourcegraph.slack.com/archives/C03CSAER9LK/p1656480594691219

Done as part of https://github.com/sourcegraph/about/issues/5513

**Comment by st0nebraker** [comment]
Closed in #5513
