### ISSUE TITLE
Small updates across pages

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5542]
Stakeholder: Fabiana and Lindsay - no need to review
What? There are various small updates required across pages on the marketing platform. 

1. Replace the Amazon logo with TBC
2. Remove 'Amazon' from this page https://about.sourcegraph.com/get-started/self-hosted
3. Link the Cloudflare logo in the carousel to https://about.sourcegraph.com/case-studies/cloudflare-accelerates-debugging-and-improves-security
4. Remove quotation marks on [Resolve incidents faster](https://about.sourcegraph.com/use-cases#:~:text=Learn%20more-,Resolve%20incidents%20faster,-Identify%20the%20root)

Why? 
1. Amazon may or may not make a decision to remove logo rights on July 7th
3. Feedback from Crazyegg data
4. The copy should not have quotation marks.

Asana: 
https://app.asana.com/0/1200095757619647/1202459307330604/f
https://app.asana.com/0/1200095757619647/1202519591393069/f

**Comment by zlonko** [comment]
@elzannewentzel I went ahead and started a draft PR for this: https://github.com/sourcegraph/about/pull/5548. Pending the finalized requirements, we only need to decide on the Amazon logo before shipping.
