### ISSUE TITLE
Update color variables

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/about#5559]
### What?
Brand Colors have recently been updated in the [Brand DLS](https://www.figma.com/file/o1QRtdQI0ozKq0n7ATrKlx/Marketing-DLS?node-id=18%3A101) & [Handbook Brand Guidelines](https://handbook.sourcegraph.com/departments/engineering/design/brand_guidelines/color/) (PR [here](https://github.com/sourcegraph/handbook/pull/4178)). We'd like our repo's color variables to be in sync with Brand colors to eliminate confusion.

---

### Why?
- To ensure developers and brand are on the same page when implementing designs.

---

### Actions Items:
1. Update changed color names.
2. Update grayscale variables.

**Comment by bretthayes** [comment]
Looks like they're already implemented according to the DLS status.
