### ISSUE TITLE
Unpublished blogposts shouldn't be viewable in prod

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/about#5620]
**Who?**: CPT
**What?**: If a blogposts frontmatter field `published` is set to false, the post slug should not be accessible in prod. If possible, allowing viewing in staging or local is favorable.
**Why?**: As an author, I expect the `published` field to do what it describes. Unpublished blog posts shouldn't show in prod.
Expected behaviour: The blog post should not show up on /blog or as a related resource, but the page/URL is still active (meaning if you have the URL, you can still access the page)

**Comment by beyang** [comment]
Actually, I believe this is the intended behavior. Unpublished posts are still accessible by direct URL, but aren't published in the main blog index. This is so we can stage content that we'd like to release and verify it renders properly in prod.
