### ISSUE TITLE
Fix CTAs on blog post template

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5663]
![Image](https://user-images.githubusercontent.com/88658267/184095417-7a5d2b3c-d5af-4dde-999d-cf1739aab651.png)

The two CTAs at the bottom of the blog post template are not displaying correctly. The CTA text should be on one line.

**Comment by elzannewentzel** [comment]
Looks like it's been fixed.

**Comment by bretthayes** [comment]
@elzannewentzel I have an updated for this as well in #5704 which swaps this component out for our new standardized `CtaSection` in as seen in our DLS 🤓
