### ISSUE TITLE
Update security page

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6003]
Update the design and copy on about.sourcegraph.com/security

[Figma shared with sourcegraph@gitstart.com](https://www.figma.com/file/vmJqkdjaf2ft5rufSRpRBV/Security-page?node-id=6%3A5&t=FvwHi9rllXQ6wPbj-1)

**Comment by fabicastp** [comment]
cc @iskyOS

**Comment by gitstart-sourcegraph** [comment]
Hello @fabicastp,
Regarding the displayed tabs in the mockup, I have noticed that the app currently utilizes different size variants of the tabs as shown in the image below (on the RHS). I have a few questions:

1. Would it be advisable to maintain consistency with the sizing used in other parts of the app?
2. Should we consider creating support for a new size variant of the tab based on the current dimensions in the mockup?
3. Alternatively, should we provide one-time support of this sizing for this particular use case alone?

Thank you.

<img width="2773" alt="image (6)" src="https://user-images.githubusercontent.com/89894075/220033384-4d3cd080-4ebb-4b7c-9806-03b90dbd2d84.png">

**Comment by fabicastp** [comment]
PR: https://github.com/sourcegraph/about/pull/6025
