### ISSUE TITLE
Livestream w/ Andre Vasnetsov (Qdrant)

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6013]
Livestream date: February 28th 

4-5 weeks after the live stream date, it will be published on /blog with a video, mp3 and notebook

To add:
- [ ] Youtube link: 
- [ ] Blog post link:
- [ ] Notebook:
- [ ] Podcast

**Comment by jdorfman** [comment]
* Sent livestream/restream invite link to Andrey
* Restream Studio is ready

**Comment by jdorfman** [comment]
@bachidegli should I upload the video to YouTube? I don't mind.
