### ISSUE TITLE
Livestream w/ Max Brunsfeld

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6014]
Livestream date: March 14

4-5 weeks after the live stream date, it will be published on /blog with a video, mp3 and notebook

To add:
- [ ] Youtube link: 
- [ ] Blog post link:
- [ ] Podcast

**Comment by jdorfman** [comment]
Gave @bachidegli the following:

* https://www.dropbox.com/sh/fym1sme7v4c3vmg/AACPU6I_GFzIVqNWapqI_u9Ma?dl=0
  * Please note there is "before-video.mov" which should be added before Beyang starts talking.
* Doc: https://docs.google.com/document/d/1vjDV5D8BGWu5Dt3ybt5WWKZO7dcZg4w0MueUECTllAE/edit#

**Comment by jdorfman** [comment]
sent audio to Paul @ Peachtreesound waiting for mp3 and notes
