### ISSUE TITLE
Livestream w/ Hassan

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6015]
Livestream date: March 21, 2023

4-5 weeks after the live stream date, it will be published on /blog with a video, mp3 and notebook

To add:
- [ ] Youtube link: 
- [ ] Blog post link:

**Comment by jdorfman** [comment]
@fabicastp updated livestream date

**Comment by bachidegli** [comment]
@jdorfman I don't see or have any pre-show notes or info from this episode. Could you share? Thanks!

**Comment by jdorfman** [comment]
@bachidegli sent you an invite
