### ISSUE TITLE
update looping video on about

### ISSUE THREAD

**Issue by adaaaam** [sourcegraph/about#627]
with the new UCS messaging, can we update the looping video on the website?

1. code search --> code discovery
2. code navigation --> code intelligence
3. code review --> the same

- remove code monitoring
- remove all other stuff :)

**Comment by ryan-blunden** [comment]
@adaaaam The video now only contains search, review, and navigate content. I'll update the title sections once I've located the artwork.

**Comment by adaaaam** [comment]
okay, awesome!
