### ISSUE TITLE
V2 Homepage updates

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6270]
CURRENT: 

- [Figma](https://www.figma.com/file/fudljjrGrUg5cDYTAo4Hra/Homepage?type=design&node-id=2078-26418&t=ReQliYU765NOrBkn-0) - Prototype page 
- See Tracey's and my comments 

**Videos** 

- Completions: https://storage.googleapis.com/sourcegraph-assets/website/Product%20Animations/cody-completion-may2023.mp4
- Fixup: https://storage.googleapis.com/sourcegraph-assets/website/Product%20Animations/cody-fixup-may2023.mp4
- Unit test: https://storage.googleapis.com/sourcegraph-assets/website/Product%20Animations/cody-unit-test-may2023.mp4
- Web chat: https://storage.googleapis.com/sourcegraph-assets/website/Product%20Animations/cody-web-chat-may2023.mp4

_____
OLD, disregard. 
See current mockup in the comments below. 

**Note the *What is Sourcegraph* section?** This section will have an interactive react embed (just a bit of orbit/panning for now). 

[Here's what we got so far. ](https://codesandbox.io/p/sandbox/sourcegraph-product-framework-diagram-copy-vr6cot) (code embed)

Spline doesn't have a SVG option. [These are the export options available](https://docs.spline.design/67b4c8ec0d2b46dd8588a99a7e94db6e) (viewer) 

Question: Which embed option works best for your team? Viewer or code embed? 

Our ultimate goal is to make our page more interactive, and this is the first step :)

**Comment by fabicastp** [comment]
![Image](https://github.com/sourcegraph/about/assets/81499360/befae144-6c04-40e8-a9a6-50a1c28d608d)

**Comment by gitstart-sourcegraph** [comment]
Hi @fabicastp, thanks for asking. Code embed option works great for the team.

**Comment by fabicastp** [comment]
- [Figma](https://www.figma.com/file/fudljjrGrUg5cDYTAo4Hra/Homepage?type=design&node-id=2078-26418&t=ReQliYU765NOrBkn-0) - Prototype page 
- See Tracey's and my comments 

**Videos** 

- Completions: https://storage.googleapis.com/sourcegraph-assets/website/Product%20Animations/cody-completion-may2023.mp4
- Fixup: https://storage.googleapis.com/sourcegraph-assets/website/Product%20Animations/cody-fixup-may2023.mp4
- Unit test: https://storage.googleapis.com/sourcegraph-assets/website/Product%20Animations/cody-unit-test-may2023.mp4
- Web chat: https://storage.googleapis.com/sourcegraph-assets/website/Product%20Animations/cody-web
