### ISSUE TITLE
Research request: Add search bar to /resources

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6285]
We are going to update about.sourcegraph.com/resources. 

An idea is to add a search bar to this page, where users could type keywords and get related content. 

We'd like to understand the complexity of this task in terms of production, functionality, cost, time, and maintenance. A couple of questions: 
- What actions would you need from us to implement the search bar?
- How much more complex would it be to update the page every time we decide to add new content?

**Comment by gitstart-sourcegraph** [comment]
Resolved in https://github.com/sourcegraph/about/pull/6301
