### ISSUE TITLE
Resources page update

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6293]
about.sourcegraph.com/resources 

🌈 [Figma](https://www.figma.com/file/n3nHcRhzmipzlSj3WvqBqi/Resources-page?type=design&node-id=1005-18595&t=1LPWx6hknWrPoNF1-0) 

[Content inventory ](https://docs.google.com/spreadsheets/d/1z7wvWV1DWNC4HSVQYyv9hJgI3K-rubUVi901--_m3e4/edit#gid=1322295915)
- Search bar column has the keywords for each content. Let me know if you have other recommendations. 
- Use placeholders if we're missing a description or a link. 
- Not all content has subject labels 
- In case it's useful to know, all content below column 30 is already in the /resources page. Please remove the Sourcegraph Overview (row 63) from the page. 

The content can be filtered by content type and subject. Horizontal logic: OR ; Vertical logic: AND. Examples: 
- Selecting GUIDE and WHITEPAPERS shows all guides and all whitepapers. 
- Selecting GUIDE and SECURITY and CODE INTELLIGENCE shows all guides with the subject security and code intelligence only. 
- Selecting GUIDE and CUSTOMER STORY and SECURITY shows all guides and customer stories with the subject security only. 

If there's no match between a content type and a subject, or no match for the search bar, the user sees the 'no results' page. 

More to come on things we'd like to track on this page...

**Comment by fabicastp** [comment]
📊 Tracking
What content cards are people clicking the most?
What content type and subject labels are getting the most clicks?
Are people clicking on the featured content?
How many times are people getting to the 'no results' page?

Let me know if you need me to loop in our analytics team. I want to make sure we have G4 and event tracking in place

**Comment by fabicastp** [comment]
Content to be featured: Big Code report (row 3 on the content calendar). 

The rest of the content can be added in the same order as the content inventory sheet.

**Comment by gitstart-sourcegraph** [comment]
Hi @fabicastp,
Would be great to loop in the analytics team, just to get some clarity on the desired event parameters for each user activity (Content cards click, Featured content click, No result page visibility)
