### ISSUE TITLE
Question: Adding TAB function to about

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6452]
We'd like to replicate how Cody's autocompletion works in our about site. The idea is to have a container with code that shows a suggestion, and when the user clicks TAB, it autocompletes. 

Similar idea to [what Github did here](https://github.com/features/copilot#:~:text=Accept-,Visual%20Studio%20Code,-max_sum_slice.py) but instead of using the buttons on right, the user would use tab to accept the suggestion. Just a little taste of how the product works. Is this possible to accomplish? How complex is it? 
___

Note: We're good with the alternative of using buttons instead of tab, so I don't want us to spend toooo much time on this research 🙂

**Comment by gitstart-sourcegraph** [comment]
> Is this possible to accomplish

We can implement a solution that caters to both desktop and mobile devices. By utilizing the Tab key functionality on desktops and incorporating buttons for tablets and mobiles.

> How complex is it

Supporting tab functionality, is not a complex feature to implement and can be achieved in a relatively short time. However we would love to get some context on the desired animation behavior of the code (on load, similar to copilot's interface), which might also contribute to spending a bit more time.

**Comment by fabicastp** [comment]
This is great to hear! We'll work on a wireframe for how we envision this function. Thank you!!

**Comment by fabicastp** [comment]
[Low-fidelity wireframe](https://create.fable.app/project/018a1a0c-f70c-72a4-82e9-847a6221d7f8/remix). Please know the colors and aesthetics are FPO and will likely change. This is just an MVP for our GitStart's team to review.


The idea is that the first line will type in, the cursor/highlight will go to the next line, then the suggestion will appear. The user will be prompted to hit Tab to accept, at which point the suggestion will change to the final state and the highlight/cursor will be below it.


Let me know if you have feedback or concerns to be able to implement this function in about. Thanks!

**Comment by fabicastp** [comment]
Update: we didn't get approval for a TAB function. Pivoting. 


Task: create an MVP for review of the following animation.

**Comment by gitstart-sourcegraph** [comment]
> Task: create an MVP prototype for review of the Autocomplete animation.

Here is the [link to the MVP](https://codesandbox.io/p/sandbox/youthful-khorana-ylv7hx). 
Thank you.

**Comment by fabicastp** [comment]
We're good to close this issue. The work will be continued on https://github.com/orgs/sourcegraph/projects/325/views/1?pane=issue&itemId=37869825
