### ISSUE TITLE
Add "About Sourcegraph" CTA to main nav in dotcom

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6462]
Add "About Sourcegraph" CTA to the main nav in sourcegraph.com 

Same font and color as the rest of the main nav. It should be on the right side of Cody. Very rough mockup attached below. 

About Sourcegraph will link to about.sourcegraph.com 

![Image](https://user-images.githubusercontent.com/81499360/262485102-ffe26764-bc79-480c-a5fb-f2d75093e032.png)

**Comment by gitstart-sourcegraph** [comment]
> Add "About Sourcegraph" CTA to the main nav in sourcegraph.com.

@fabicastp We have push a Pull Request [here](https://github.com/sourcegraph/sourcegraph/pull/56228).
Kindly take a look.
