### ISSUE TITLE
Discovery: Move about.sourcegraph.com to sourcegraph.com

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6469]
Hi team! We're looking into moving about.sourcegraph.com to sourcegraph.com 

I'd like to know more about the **technical feasibility** of this move. What changes should we expect to the code and file configuration (or anything else)? What questions would we need to answer for you to kick off this work? Is this something your team could support? 

No need to dig too deep, as I'm just looking for a list of things we need to consider to make this change (from a technical POV).

**Comment by fabicastp** [comment]
Let me know when we can expect an update, please 😄

**Comment by fabicastp** [comment]
Hi team! To answer your question, we'd like to integrate the about pages as part of the sourcegraph app. We want sourcegraph.com to be a marketing page.

In my limited experience working with you on sourcegraph.com, I know this can present its challenges. Please flag concerns and keep the questions coming!

**Comment by gitstart-sourcegraph** [comment]
Hi Team,
#### Here is our thoughts on integrating the marketing app with the [sourcegraph.com](http://sourcegraph.com/) app.
1. We should first replace next/ API usages with shared components in [SourceGraph.com](http://sourcegraph.com/) if exists or implement relevant ones.
2. We can then move the layout and  the individual pages into the web package.
3. [sourcegraph.com](http://sourcegraph.com/) is not currently optimized for SEO. To address this, we can consider implementing *Static Site Generation (SSG)* for the marketing pages. However, we need to further investigate the feasibility of this approach.

Thank you. :blush:

**Comment by jdorfman** [comment]
This is done. Closing
