### ISSUE TITLE
Sharing the link to the marketing site shows "Application Error" icon and message

### ISSUE THREAD

**Issue by amieroth** [sourcegraph/about#6570]
When I share the link to about.sourcegraph.com through iMessage, it shows the following image:

![Image](https://github.com/sourcegraph/about/assets/57014955/0440a15e-33d9-477f-9da9-5ceacf65e492)

**Comment by gitstart-sourcegraph** [comment]
Fixed [here](https://github.com/sourcegraph/about/pull/6638)
