### ISSUE TITLE
Syntax highlighting loads then breaks

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/about#6588]
Check out the video:

https://github.com/sourcegraph/about/assets/398230/bcd3b92b-a116-4e6e-984b-953ce7c3ebc4

Link to issue: https://deploy-preview-6586--sourcegraph.netlify.app/blog/guest-post-arafat-khan-php-python#:~:text=You%20can%20see%20how%20easy%20it%20is%20to%20select%20some%20Python%20code%20and%20ask%20Cody%20to%20convert%20it.%20This%20gives%20us%20a%20good%20starting%20point%20of%20the%20outline%20of%20the%20class%20that%20we%20are%20looking%20for.

**Comment by gitstart-sourcegraph** [comment]
Hi @jdorfman 
After speccing this issue, we realized that we don't have the source code for `blog/guest-post-arafat-khan-php-python`.
Which has blocked us from making any significant progress debugging the issue.

Any assistance in obtaining the necessary source code is appreciated.
Thank you.

**Comment by jdorfman** [comment]
Hey @gitstart-sourcegraph sorry about that.

This: https://deploy-preview-6586--sourcegraph.netlify.app/blog/guest-post-arafat-khan-php-python

PR: https://github.com/sourcegraph/about/pull/6586

**Comment by gitstart-sourcegraph** [comment]
Thank you @jdorfman.
We're on it.
