### ISSUE TITLE
Low-contrast/busy background on homepage

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#659]
The new starry universe background looks great overall, but it is too low-contrast/busy IMO with respect to the text. It is a bit hard to read, and it looks like a mistake/oversight.

![image](https://user-images.githubusercontent.com/1976/76496724-da12ef00-63f6-11ea-9fc0-b035fc954f88.png)

The 2 red arrows are:

- The Sourcegraph logo mark is hard to see because it is right on top of a white cluster of stars on my monitor. If I make my window narrower, this is no longer a problem, but the white cluster of stars makes some other text harder to read instead.
- The "Enter work email" field is low-constrast with the background.

**Comment by aileenrose** [comment]
I'll review the bg to make it slighter darker and also look at the text.
