### ISSUE TITLE
Community page button CSS broken on Safari

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/about#6663]
Page: https://sourcegraph.com/community

Buttons:

<img width="909" alt="Image 2023-12-20 at 10 19 46 AM png" src="https://github.com/sourcegraph/about/assets/398230/798bd6c0-f74c-4293-bb09-bcf6dc4d6b20">

**Comment by gitstart-sourcegraph** [comment]
Hi @jdorfman 
Pushed a fix.

**Comment by jdorfman** [comment]
LGTM ty
