### ISSUE TITLE
Code Search product page revision

### ISSUE THREAD

**Issue by iskyOS** [sourcegraph/about#6705]
We'd like to iterate on our Code Search product page (sourcegraph.com/code-search). We have the first iteration design ready for development.

Here is the design, on the page titled "Mockups (we are here)"
[Figma](https://www.figma.com/file/mHXhTWrUjEquh9Uhlg5uDc/Code-Search-page?type=design&node-id=423-3069&mode=design&t=xqa4rje7JePNoMEQ-0)

The primary changes are:

- We are introducing a new lighter color theme for the page
- We are centering the header, with a new hero image
- We're updating the logo pond to the carousel 
- For the 4 primary product sections of the page, we are tweaking some of the copy
- We are reworking several elements at the bottom of the page, including the CTAs
- We're adding customer quotes

**Comment by traceyljohnson** [comment]
@gitstart-sourcegraph Can you update the OG image for this page too? New image is attached. 
![Code search og image](https://github.com/sourcegraph/about/assets/102541294/63dfb701-3fa5-443c-ba09-7ad101f205bc)
