### ISSUE TITLE
Solutions page [Gitlab]

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6800]
🔗[Figma](https://www.figma.com/file/HawFaBocHLKdMVMJD5Gxxl/Integrations-page-template?type=design&node-id=1-1576&mode=design&t=0nFo2WsaQQU26N86-0)

URL: sourcegraph.com/solutions/code-intelligence-for-gitlab

Title tag: Code intelligence for GitLab

Meta description: 
Enhance your GitLab experience with Sourcegraph's Code intelligence platform. Try Cody for contextual code writing, command generation, and AI autocompletion. Get seamless integration, code search, personalized code insights, and automation for large-scale code changes.  Perfect for developers looking to streamline their workflow and understand their codebase at any scale. Contact us for a demo or start an enterprise trial today.

**Comment by gitstart-sourcegraph** [comment]
Hi @fabicastp 
May you please grant us access to the figma?
Thank you

**Comment by traceyljohnson** [comment]
@gitstart-sourcegraph here is the compressed webp! Let me know if you need a different format. [cody-generating-code.webp.zip](https://github.com/sourcegraph/about/files/14559694/cody-generating-code.webp.zip)
