### ISSUE TITLE
Code Search vs GitHub code search page

### ISSUE THREAD

**Issue by kelvinyap** [sourcegraph/about#6881]
We want to create a new comparison page that will have a similar URL to our other comparison pages, and be discoverable in https://sourcegraph.com/resources.

**URL for page:** sourcegraph.com/compare/github-vs-code-search
**Page title:** Sourcegraph Code Search vs GitHub code search
**Page description:** Feature comparison of Sourcegraph Code Search and GitHub code search

**Content:** Please see the following doc for content: https://docs.google.com/document/d/1ub0fvLfLvVZ3whvVnUj8xxm4vdQdQmPiIjy7nYva5Ws/edit?usp=sharing

**Layout:** This page should use the same template as our other comparison pages, e.g. https://sourcegraph.com/compare/copilot-vs-cody

**Discoverability:** Please see the following doc for instructions on how we want to make the pages discoverable: https://docs.google.com/document/d/1OzwvCWR4ahxWefNlCMw8uEhzREq7dr1U8dxLX19qTio/edit?usp=sharing

Note: We'll need a new hero image at the top of the page, so please leave a placeholder image until I can add the proper one to this issue.

![Image](https://github.com/sourcegraph/about/assets/4042908/b68be3cf-5f62-4b95-ac2c-bb767eb6b790)

**Comment by gitstart-sourcegraph** [comment]
> Hero image added:

Thank you @kelvinyap
