### ISSUE TITLE
Fix alternate text for logo

### ISSUE THREAD

**Issue by AnandChowdhary** [sourcegraph/about#693]
This is a minor issue after #692.

### Current markup

The `.navbar-brand` link contains an image with the Sourcegraph logo, the first item in the header:

```html
<img src="/sourcegraph/logo--light.svg" alt="Sourcegraph logo">
```

### Correct markup

```html
<img src="/sourcegraph/logo--light.svg" alt="Sourcegraph">
```

The alternate text (`alt` attribute) should be "Sourcegraph", not "Sourcegraph logo"

### Why

Intuitively, the logo is a representation of the company name. When a screen reader reads the image, it should say "Sourcegraph / link", implying the home page of the company, rather than "Sourcegraph logo / link", implying a decorative image of the logo.

Specifically, [Writing effective ALT text for images](https://inviqa.com/blog/writing-effective-alt-text-images) recommends:

> Websites tend to vary in how they apply ALT text to logos. Some say, ‘Company name’, others ‘Company name logo’, and others describe the function of the image (usually a link back to the homepage) e.g. ‘Back to home’. Remember, ALT text should always describe the content of the image so the first example, alt="Company name", is probably the best.

**Comment by ryan-blunden** [comment]
Thanks @AnandChowdhary!
