### ISSUE TITLE
Add other issue templates or remove the one copy-specific one 

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#7]
This looks like a barrier to filing an issue for an external user 

![3551d97a-ab36-4114-abff-f8348e944f72](https://user-images.githubusercontent.com/1976/46472014-67611580-c7f9-11e8-937b-aedec618c9e1.png)

**Comment by sqs** [comment]
@ryan-blunden IMO having the copy editing issue template there makes it seem like we don't want people to file other issues (because of the way GitHub presents the UI). You should either create more issue templates for general bugs, or remove the copy editing issue template.

**Comment by ryan-blunden** [comment]
I'll remove it as its not needed.
