### ISSUE TITLE
Update design on /batch-changes

### ISSUE THREAD

**Issue by traceyljohnson** [sourcegraph/about#7101]
[Figma](https://www.figma.com/design/kEcqnqKLFx9Cg9aIkJBRYI/%2Fbatch-changes?m=dev&focus-id=302-6031)

Content is mostly the same with a few exceptions (please update in those instances you find). This is mainly a design update. Please use existing components wherever possible (you can see whether its been detached in Dev Mode). If a new component section needs to be created or an existing component needs to be edited to match the design, please let @traceyljohnson know so we can figure out how to proceed. Trying to reduce the number of components needed! Thank you!

**Comment by gitstart-sourcegraph** [comment]
Hi @traceyljohnson 
These will be the major updates on the `/batch-changes page`

### UI Changes

1. Component Hero below needs to be editted, spacing, text color plus "Talk to an engineer" button style doesnt match figma
<img width="1445" alt="batch-hero" src="https://github.com/user-attachments/assets/ece239e4-0b54-49e9-ab1d-3cd0854ef90b">


2. We will reuse the component found on the https://sourcegraph.com/. We will update it to match figma
Current
<img width="813" alt="Screenshot 2024-07-24 at 14 42 09" src="https://github.com/user-attachments/assets/16dcb619-90c3-46b2-90f9-82681f384aca">

Figma:
<img width="819" alt="Screenshot 2024-07-24 at 14 42 18" src="https://github.com/user-attachments/assets/40238c5b-9f0e-42b3-b641-2f6170c187a9">

3. The Heading border in the Tabs component below is longer than figma, requires a slight change, it also lacks the bottom link

Current:
<img width="889" alt="Screenshot 2024-07-24 at 14 43 57" src="https://github.com/user-attachments/assets/027e955b-de50-4274-a3a9-f7def44ad224">

Figma:
<img width="668" alt="Screenshot 2024-07-24 at 14 44 21" src="https://github.com/user-attachments/assets/703e00d3-da07-41d5-bc06-a6d9e7176f5b">

4. We will refactor the  `CodyCta  component` and reuse it.
Current:
<img width="820" alt="Screenshot 2024-07-24 at 14 46 52" src="https://github.com/user-attachments/assets/93d2bef2-ad94-4728-bdde-739ca993a695">

Figma:

<img width="843" alt="Screenshot 2024-07-24 at 14 47 02" src="https://github.com/user-attachments/assets/75f3f54d-3720-429f-b220-328836b6024c">

Thank you
