### ISSUE TITLE
New webpage: enterprise trial page

### ISSUE THREAD

**Issue by iskyOS** [sourcegraph/about#7108]
We would like to build a new webpage, which will be used to capture enterprise trials.

The page design is in Figma here. There are notes listed in Dev Mode: https://www.figma.com/design/nUnON7wPg3ImOf9z5xFYI6/%2Fenterprise%2Ftrial?node-id=14-376&t=TznpCvbIg0vaUs3L-0

**Metadata for the page**: 
URL: http://sourcegraph.com/enterprisetrialoffer
Page title: Cody | Enterprise Trial Offer
Meta Description: Get started with a trial of Cody Enterprise to try the AI coding assistant with your team.

For the HubSpot form on the page, please reuse the form available on this page: https://sourcegraph.com/contact/request-info?form_submission_source=request-info

**Comment by githubbrittani** [comment]
@gitstart-sourcegraph further clarification on the form.

Here is the script: 

<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "na1",
    portalId: "2762526",
    formId: "e090296f-84f5-4bcb-9093-a533336841b4"
  });
</script>

It is the same form on this page: https://sourcegraph.com/contact/request-info?form_submission_source=request-info

We'll need to update the **form submission source** to `cody-enterprise-trial`

**Comment by traceyljohnson** [comment]
@brittani.ferguson Can we update the submit button design to match our new primary buttons? [Design specs here ](https://www.figma.com/design/o1QRtdQI0ozKq0n7ATrKlx/Marketing-DLS?m=auto&node-id=652-14&t=GYLaFRj3UoEJWW81-1)
