### ISSUE TITLE
Add Google mention to code change management page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#715]
https://mobile.twitter.com/fatih/status/1244326321292849154 from the new Google SWE book describes code change management in use at Google. We should cite this on the code change management page as we do for Google/Facebook's use of code search on the code search page.

HT to @beyang on Slack at https://sourcegraph.slack.com/archives/C0LJP8WTB/p1585512391011300

**Comment by adaaaam** [comment]
updated with quote - lmk if that works?
