### ISSUE TITLE
Logos are showing up wrong on homepage

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#7164]
On Sourcegraph.com the logos are half hidden and are left-aligned:
<img width="1840" alt="image" src="https://github.com/user-attachments/assets/4ceefe8d-8868-4b38-be98-9bb6ce083f86">

**Comment by kukicado** [comment]
Hmm I am unable to recreate this issue.

What it looks like for me:

![CleanShot 2024-08-22 at 12 16 07@2x](https://github.com/user-attachments/assets/1825489b-4e92-4b88-8539-9ec72fac59b6)

Will dive deeper

**Comment by jdorfman** [comment]
Weird, I can't replicate it in Chrome, Firefox, or Safari
