### ISSUE TITLE
Add Changelog OG image

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/about#7192]
![changelog-og-image-compressed.png](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/6a596512-53a6-4239-8f25-b0c148843ab2/36db876e-79a6-412a-a6aa-8ffe0587dbe5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy82YTU5NjUxMi01M2E2LTQyMzktOGYyNS1iMGMxNDg4NDNhYjIvMzZkYjg3NmUtNzlhNi00MTJhLWE2YWEtOGZmZTA1ODdkYmU1IiwiaWF0IjoxNzI1ODkzMjAyLCJleHAiOjMzMjk2NDUzMjAyfQ.odqAaD2YQSnsT6lPthceNN3ny9FxXTiMx1Y-e7nnzuU "=1200x")

Please add to Changelog index page and to Changelog child pages as default.

**Comment by MaedahBatool** [comment]
@jdorfman are you trying to get an image for this URL: https://sourcegraph.com/changelog?topics=Cody?

**Comment by jdorfman** [comment]
@MaedahBatool yes I want to share it on Discord and X

**Comment by MaedahBatool** [comment]
Let me get that image from @traceyljohnson.
