### ISSUE TITLE
Document the process for publishing a blog post

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/about#740]
This documentation should answer questions like:
- How do I request review for a blog post?
- Should I write my blog post as a Google Doc or as a markdown file?
- How long does it take to get approval and copy edits done?
- Who needs to approve before I merge?

**Comment by nicksnyder** [comment]
Current technical docs: https://github.com/sourcegraph/about#adding-a-blog-post

**Comment by slimsag** [comment]
- Where do I upload images?

Stephen's opinion:

> Images should be uploaded to [the `sourcegraph-assets/about.sourcegraph.com` Google Cloud Storage bucket](https://console.cloud.google.com/storage/browser/sourcegraph-assets/about.sourcegraph.com/?forceOnBucketsSortingFiltering=false&authuser=1&folder&organizationId&project=sourcegraph-dev) and [linked to like this](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/about%24+sourcegraph-assets&patternType=literal)

**Comment by ryan-blunden** [comment]
Do you think we should do that for all images?
