### ISSUE TITLE
Document how to use the HubSpot Chrome extension for email logging and tracking

### ISSUE THREAD

**Issue by sqs** [sourcegraph/about#759]
All sales team members would benefit from getting HubSpot integrated into their Gmail for email logging and tracking. This is vaguely mentioned at https://about.sourcegraph.com/handbook/sales/onboarding#day-1 but it doesn't explain what that means and how to do it.

**Comment by mercadon** [comment]
I'm not sure if I'm the best person to own this, I know it's listed under People Ops right now but that should probably be adjusted since I'm not an admin on HubSpot (or even a user, heh). @juliasourceress are you the HubSpot admin and is this an account that would be primarily Sales specific?

**Comment by juliasourceress** [comment]
Closing this out as it no longer applies.
