### ISSUE TITLE
dotGo Paris

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/about#91]
Tracking issue for dotGo Paris.

Important info on [Google docs](https://docs.google.com/document/d/1a4xoK8CMoIa4pYtnFk3S9X0t0RtbkKg5HZNSPXFIe0M/edit#)

## Media and content

- [x] Logo uploaded (@francisschmaltz )
- [x] Poster uploaded (@francisschmaltz)
- [x] Online content (@ryan-blunden )
- [x] Newsletter content (@ryan-blunden)
- [x] Design and print Sourcegraph tee/hoodie @francisschmaltz 

## Logistics

- [x] Stand setup: @ryan-blunden @francisschmaltz 
- [x] Goodies chosen and sent
- [ ] Swag, Stickers
- [x] Google form for capturing details

## At the booth

- [x] Fix up Sourcegraph.com with key use-cases
- [x] Have list of useful searches from docs page
- [x] Have a case study for a takeaway

**Comment by francisschmaltz** [comment]
Poster was sent in email as bleeded CMYK PDF
