### ISSUE TITLE
Banner and logo for UBC Launchpad webinar

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/about#92]
Media required for the UBC Launchpad sourcegraph Webinar taking place on March 30.

- [ ] Sourcegraph logos's (light and dark)
- [ ] Event banner/hero image with our logo [and theirs](https://www.ubclaunchpad.com/img/share-logo.png) (like this [GitLab banner](https://www.ubclaunchpad.com/img/share-logo.png))

**Comment by bobheadxi** [comment]
Thanks for the update @ryan-blunden - the linked logo is a bit out of date, more recent ones are available here:

https://drive.google.com/open?id=1R219ibHvVqOMzDI0prqiRWMcCyuQXcGj

Examples of the designs we are using for our event series, "Project Hub" (which this webinar will be a part of):

* https://github.com/ubclaunchpad/ubclaunchpad.github.io/blob/master/project-hub/feb2.jpg
* https://www.facebook.com/events/298511734161391/
* https://www.facebook.com/ubclaunchpad/photos/a.1457037324611562/2167500580231896

Just ping @cowjuh or me if you need anything!
