### ISSUE TITLE
3.2 Tweet

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/about#96]
Sourcegraph 3.2 is out! OSS/self-hosted code search/nav tool, now with:

ℹ️ Onboarding flow for site admins and users
🌐 Easier deployment to EC2 and DigitalOcean
🔒 Better SSL documentation
🔎 Integrations refactoring and code intelligence improvements

https://about.sourcegraph.com/blog/sourcegraph-3.2

**Comment by sqs** [comment]
To reiterate the focus on polish of the release, my suggestion:

---

Sourcegraph 3.2 is here! The open-source, self-hosted code search/nav tool, now with:

ℹ️ User/admin onboarding!
🌐 Easier SSL, EC2, and DigitalOcean deploy docs
🏗️ Tons of polish improvements & tech debt cleanups to power future awesome features

https://about.sourcegraph.com/blog/sourcegraph-3.2

**Comment by ryan-blunden** [comment]
Using your version
