### ISSUE TITLE
Pricing page is confusing

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/about#98]
Our pricing page can be confusing. A user that viewed our pricing page had the following questions: 

- Do we have a user cap for the free tier?
- What is the user cap for the free tier?
- Is the user cap based on max or concurrent users?

These questions should be answered by the pricing page.

**Comment by sqs** [comment]
The pricing page answers these questions now.

**Comment by Fish013** [comment]
> The pricing page answers these questions now.

No it doesn't, at least not anymore. What user limitations does the free tier have and which features are missing?
